"""PyCoach curriculum: short explanations, deliberate practice, and progressive hints."""

LESSONS = [
    {
        "id": "hello-print", "order": 1, "unit": "출력", "title": "화면에 글자 보여주기",
        "concept": "print()는 컴퓨터에게 “이 내용을 화면에 보여줘”라고 말하는 명령입니다.",
        "why": "코드를 실행한 결과를 확인할 때 가장 먼저 쓰는 도구예요.",
        "example": 'print("안녕하세요")', "exampleOutput": "안녕하세요",
        "prompt": "화면에 “안녕하세요”를 출력해 보세요.",
        "starterCode": "# 여기에 코드를 작성해 보세요\n", "expectedOutput": "안녕하세요",
        "hints": ["화면에 내용을 보여줄 때 쓰는 함수를 떠올려 보세요.", "글자는 큰따옴표 또는 작은따옴표로 감쌉니다.", 'print("안녕하세요")'],
        "summary": "print()는 값을 화면에 출력합니다.", "estimatedMinutes": 7,
    },
    {
        "id": "my-name", "order": 2, "unit": "출력", "title": "내 이름 출력하기",
        "concept": "문자열은 따옴표로 감싼 글자 데이터입니다.",
        "why": "이름이나 메시지처럼 계산하지 않을 글자를 컴퓨터에게 알려 주기 위해 필요해요.",
        "example": 'print("피터")', "exampleOutput": "피터",
        "prompt": "본인의 이름을 화면에 출력해 보세요.",
        "starterCode": "# 따옴표 안에 본인의 이름을 넣어 보세요\n", "expectedOutput": "",
        "checkType": "non_empty_output",
        "hints": ["이름도 글자 데이터예요.", "글자는 따옴표로 감싸야 합니다.", 'print("피터")  # 피터 부분을 본인 이름으로 바꿔 보세요'],
        "summary": "글자를 출력할 때는 따옴표를 사용합니다.", "estimatedMinutes": 6,
    },
    {
        "id": "two-lines", "order": 3, "unit": "출력", "title": "두 줄로 안내하기",
        "concept": "print()를 여러 번 쓰면 각 결과가 새 줄에 표시됩니다.",
        "why": "프로그램의 안내 문구를 읽기 쉬운 형태로 만들 수 있어요.",
        "example": 'print("파이썬")\nprint("시작!")', "exampleOutput": "파이썬\n시작!",
        "prompt": "첫 줄에 “파이썬”, 둘째 줄에 “시작!”을 출력해 보세요.",
        "starterCode": "# print()를 두 번 사용해 보세요\n", "expectedOutput": "파이썬\n시작!",
        "hints": ["한 줄을 출력하는 print()를 두 번 써 보세요.", "각 print()의 괄호 안에 한 문장씩 넣습니다.", 'print("파이썬")\nprint("시작!")'],
        "summary": "print() 하나가 한 줄의 결과를 만듭니다.", "estimatedMinutes": 7,
    },
    {
        "id": "study-message", "order": 4, "unit": "출력", "title": "나만의 학습 문장",
        "concept": "print() 안에는 원하는 문장을 넣을 수 있습니다.",
        "why": "작은 출력부터 만들면 프로그램이 무엇을 하는지 눈으로 바로 확인할 수 있어요.",
        "example": 'print("오늘도 한 걸음!")', "exampleOutput": "오늘도 한 걸음!",
        "prompt": "“이해하며 배우는 파이썬”을 출력해 보세요.",
        "starterCode": "# 문장을 출력해 보세요\n", "expectedOutput": "이해하며 배우는 파이썬",
        "hints": ["출력할 문장은 따옴표 안에 넣습니다.", "문장 전체를 하나의 문자열로 생각해 보세요.", 'print("이해하며 배우는 파이썬")'],
        "summary": "문자열은 공백을 포함한 문장도 담을 수 있습니다.", "estimatedMinutes": 6,
    },
    {
        "id": "variable-message", "order": 5, "unit": "변수", "title": "값에 이름 붙이기",
        "concept": "변수는 값을 담아 두고 다시 꺼내 쓰기 위한 이름표입니다.",
        "why": "같은 값을 여러 번 쓰지 않고, 의미 있는 이름으로 코드를 읽기 쉽게 만들어요.",
        "example": 'language = "파이썬"\nprint(language)', "exampleOutput": "파이썬",
        "prompt": "변수 language에 “파이썬”을 저장한 뒤 출력해 보세요.",
        "starterCode": "# language라는 변수에 값을 넣어 보세요\n", "expectedOutput": "파이썬",
        "codeRequirements": {"requiredVariableNames": ["language"]},
        "hints": ["변수에 값을 저장할 때는 = 기호를 사용합니다.", 'language = "파이썬"처럼 왼쪽에 이름, 오른쪽에 값을 둡니다.', 'language = "파이썬"\nprint(language)'],
        "summary": "변수 이름으로 저장한 값을 다시 사용할 수 있습니다.", "estimatedMinutes": 9,
    },
    {
        "id": "variable-calculation", "order": 6, "unit": "변수", "title": "변수로 계산하기",
        "concept": "숫자도 변수에 저장한 뒤 사칙연산에 사용할 수 있습니다.",
        "why": "가격, 점수, 개수처럼 바뀔 수 있는 값을 관리할 때 유용해요.",
        "example": "price = 8000\ncount = 3\nprint(price * count)", "exampleOutput": "24000",
        "prompt": "price에 8000, count에 3을 저장하고 곱한 결과를 출력해 보세요.",
        "starterCode": "# 가격과 개수를 변수에 저장해 보세요\n", "expectedOutput": "24000",
        "codeRequirements": {"requiredVariableNames": ["price", "count"], "requiredOperators": ["multiply"]},
        "hints": ["숫자는 따옴표 없이 저장합니다.", "곱셈 기호는 * 입니다.", "price = 8000\ncount = 3\nprint(price * count)"],
        "summary": "숫자 변수는 계산식 안에서 바로 쓸 수 있습니다.", "estimatedMinutes": 10,
    },
    {
        "id": "string-concat", "order": 7, "unit": "변수", "title": "글자 이어 붙이기",
        "concept": "문자열끼리는 + 기호로 이어 붙일 수 있습니다.",
        "why": "여러 조각의 메시지를 조합해 개인화된 안내 문구를 만들 수 있어요.",
        "example": 'first = "오늘도 "\nsecond = "파이썬"\nprint(first + second)', "exampleOutput": "오늘도 파이썬",
        "prompt": "first에 “오늘도 ”, second에 “파이썬”을 저장하고 이어서 출력해 보세요.",
        "starterCode": "# 두 문자열을 + 로 이어 보세요\n", "expectedOutput": "오늘도 파이썬",
        "codeRequirements": {"requiredVariableNames": ["first", "second"], "requiredOperators": ["add"]},
        "hints": ["첫 번째 문자열 끝에는 공백이 하나 있어요.", "문자열도 +로 더할 수 있습니다.", 'first = "오늘도 "\nsecond = "파이썬"\nprint(first + second)'],
        "summary": "문자열의 +는 계산이 아니라 글자 연결입니다.", "estimatedMinutes": 9,
    },
    {
        "id": "f-string", "order": 8, "unit": "변수", "title": "문장에 변수 넣기",
        "concept": "f 문자열은 문장 안에 변수 값을 자연스럽게 넣는 방법입니다.",
        "why": "이름, 점수, 날짜처럼 달라지는 정보를 문장으로 보여줄 때 편리해요.",
        "example": 'name = "피터"\nprint(f"{name}님, 시작해요!")', "exampleOutput": "피터님, 시작해요!",
        "prompt": "name에 “피터”를 저장하고 f 문자열로 “피터님, 시작해요!”를 출력해 보세요.",
        "starterCode": "# f 문자열을 사용해 보세요\n", "expectedOutput": "피터님, 시작해요!",
        "codeRequirements": {"requiredVariableNames": ["name"], "requiredSyntax": ["fString"]},
        "hints": ["문자열 맨 앞에 f를 붙입니다.", "변수 이름은 중괄호 { } 안에 넣습니다.", 'name = "피터"\nprint(f"{name}님, 시작해요!")'],
        "summary": "f 문자열의 {변수} 자리에 실제 값이 들어갑니다.", "estimatedMinutes": 10,
    },
    {
        "id": "input-greeting", "order": 9, "unit": "입력", "title": "사용자에게 이름 받기",
        "concept": "input()은 프로그램을 사용하는 사람에게 값을 입력받는 함수입니다.",
        "why": "사용자마다 다른 결과를 보여 주는 프로그램의 시작점이에요.",
        "example": 'name = input()\nprint(f"{name}님, 반가워요!")', "exampleOutput": "피터님, 반가워요!",
        "prompt": "이름을 input()으로 받아 “피터님, 반가워요!”처럼 출력해 보세요. (테스트 입력값: 피터)",
        "starterCode": "# input()으로 이름을 받아 보세요\n", "expectedOutput": "피터님, 반가워요!", "inputs": ["피터"],
        "codeRequirements": {"requiredVariableNames": ["name"], "requiredCalls": ["input"], "requiredSyntax": ["fString"], "testCases": [{"inputs": ["민수"], "expectedOutput": "민수님, 반가워요!"}]},
        "hints": ["input()의 결과를 name 변수에 저장해 보세요.", "문장 안에 name을 넣을 때 f 문자열을 써 보세요.", 'name = input()\nprint(f"{name}님, 반가워요!")'],
        "summary": "input()으로 받은 값은 변수에 저장해 사용합니다.", "estimatedMinutes": 11,
    },
    {
        "id": "age-next-year", "order": 10, "unit": "입력", "title": "입력값을 숫자로 바꾸기",
        "concept": "input()으로 받은 값은 글자이므로, 계산하려면 int()로 정수로 바꿉니다.",
        "why": "나이, 수량, 금액처럼 계산할 정보는 숫자형으로 바꿔야 해요.",
        "example": "age = int(input())\nprint(age + 1)", "exampleOutput": "21",
        "prompt": "나이를 입력받아 1을 더한 값을 출력해 보세요. (테스트 입력값: 20)",
        "starterCode": "# input() 값에 int()를 적용해 보세요\n", "expectedOutput": "21", "inputs": ["20"],
        "codeRequirements": {"requiredVariableNames": ["age"], "requiredCalls": ["input", "int"], "requiredOperators": ["add"], "testCases": [{"inputs": ["33"], "expectedOutput": "34"}]},
        "hints": ["input() 결과를 바로 더하면 글자와 숫자가 섞입니다.", "int(input()) 형태를 만들어 보세요.", "age = int(input())\nprint(age + 1)"],
        "summary": "int()는 숫자처럼 보이는 글자를 정수로 바꿉니다.", "estimatedMinutes": 11,
    },
    {
        "id": "sum-two-values", "order": 11, "unit": "입력", "title": "두 숫자 더하기",
        "concept": "입력을 여러 번 받아도 각각 다른 변수에 저장할 수 있습니다.",
        "why": "계산기처럼 여러 값을 조합하는 프로그램을 만들 수 있어요.",
        "example": "first = int(input())\nsecond = int(input())\nprint(first + second)", "exampleOutput": "20",
        "prompt": "두 숫자를 입력받아 합을 출력해 보세요. (테스트 입력값: 12, 8)",
        "starterCode": "# 두 번 입력받아 더해 보세요\n", "expectedOutput": "20", "inputs": ["12", "8"],
        "codeRequirements": {"requiredVariableNames": ["first", "second"], "requiredCalls": ["int"], "minimumCallCounts": {"input": 2}, "requiredOperators": ["add"], "testCases": [{"inputs": ["5", "7"], "expectedOutput": "12"}]},
        "hints": ["입력값마다 변수 하나가 필요합니다.", "두 input() 모두 int()로 감싸 보세요.", "first = int(input())\nsecond = int(input())\nprint(first + second)"],
        "summary": "입력값을 변수로 나누면 계산 과정을 읽기 쉬워집니다.", "estimatedMinutes": 12,
    },
    {
        "id": "score-check", "order": 12, "unit": "연산", "title": "점수 기준 확인하기",
        "concept": "비교 연산자는 두 값을 비교해 True 또는 False 결과를 만듭니다.",
        "why": "다음 단계의 조건문 if가 어떤 판단을 하는지 이해하는 기초가 됩니다.",
        "example": "score = 85\nprint(score >= 80)", "exampleOutput": "True",
        "prompt": "score에 85를 저장하고, score가 80 이상인지 출력해 보세요.",
        "starterCode": "# >= 비교 연산자를 사용해 보세요\n", "expectedOutput": "True",
        "codeRequirements": {"requiredVariableNames": ["score"], "requiredOperators": ["greaterOrEqual"]},
        "hints": ["80 이상은 >= 기호로 표현합니다.", "비교 결과는 True 또는 False로 나옵니다.", "score = 85\nprint(score >= 80)"],
        "summary": ">=는 왼쪽 값이 오른쪽 값 이상인지 확인합니다.", "estimatedMinutes": 9,
    },
    {
        "id": "average-share", "order": 13, "unit": "연산", "title": "나누기 계산하기",
        "concept": "/ 기호는 나눗셈을 뜻하며, 결과는 소수점이 있는 숫자가 될 수 있습니다.",
        "why": "평균, 단가, 비율처럼 데이터를 다룰 때 자주 쓰입니다.",
        "example": "total = 28\npeople = 4\nprint(total / people)", "exampleOutput": "7.0",
        "prompt": "total에 28, people에 4를 저장하고 한 사람당 몫을 출력해 보세요.",
        "starterCode": "# / 연산자로 나누어 보세요\n", "expectedOutput": "7.0",
        "codeRequirements": {"requiredVariableNames": ["total", "people"], "requiredOperators": ["divide"]},
        "hints": ["나눗셈 기호는 / 입니다.", "변수 두 개를 먼저 만들고 나눕니다.", "total = 28\npeople = 4\nprint(total / people)"],
        "summary": "/의 결과는 정수끼리 나눠도 7.0처럼 표시될 수 있습니다.", "estimatedMinutes": 9,
    },
    {
        "id": "profile-mission", "order": 14, "unit": "미니 미션", "title": "나의 학습 프로필",
        "concept": "입력, 변수, f 문자열을 함께 사용하면 나만의 문장을 만들 수 있습니다.",
        "why": "문법 하나씩을 외우기보다, 함께 조합해 보는 순간 연결이 생깁니다.",
        "example": 'name = input()\nsubject = "데이터 분석"\nprint(f"{name}님은 {subject}을 배우고 있어요.")', "exampleOutput": "피터님은 데이터 분석을 배우고 있어요.",
        "prompt": "이름을 input()으로 받고 subject에 “데이터 분석”을 저장하세요. 마지막에 f 문자열로 “피터님은 데이터 분석을 배우고 있어요.”를 출력해 보세요. (테스트 입력값: 피터)",
        "starterCode": "# 배운 문법을 조합해 보세요\n", "expectedOutput": "피터님은 데이터 분석을 배우고 있어요.", "inputs": ["피터"],
        "codeRequirements": {"requiredVariableNames": ["name", "subject"], "requiredCalls": ["input"], "requiredSyntax": ["fString"], "testCases": [{"inputs": ["민수"], "expectedOutput": "민수님은 데이터 분석을 배우고 있어요."}]},
        "hints": ["name에는 input()의 결과를 저장합니다.", "subject에는 따옴표로 감싼 문자열을 저장합니다.", 'name = input()\nsubject = "데이터 분석"\nprint(f"{name}님은 {subject}을 배우고 있어요.")'],
        "summary": "작은 프로그램은 이미 배운 문법의 조합으로 만들어집니다.", "estimatedMinutes": 12,
    },
    {
        "id": "shopping-mission", "order": 15, "unit": "미니 미션", "title": "장바구니 금액 계산기",
        "concept": "입력받은 숫자와 곱셈을 조합하면 실제 계산기를 만들 수 있습니다.",
        "why": "가격과 수량을 분리하면 다양한 상품에 같은 계산 로직을 적용할 수 있어요.",
        "example": "price = int(input())\ncount = int(input())\nprint(price * count)", "exampleOutput": "10500",
        "prompt": "가격과 수량을 입력받아 총 금액을 출력해 보세요. (테스트 입력값: 3500, 3)",
        "starterCode": "# 가격 × 수량을 계산해 보세요\n", "expectedOutput": "10500", "inputs": ["3500", "3"],
        "codeRequirements": {"requiredVariableNames": ["price", "count"], "requiredCalls": ["int"], "minimumCallCounts": {"input": 2}, "requiredOperators": ["multiply"], "testCases": [{"inputs": ["1200", "4"], "expectedOutput": "4800"}]},
        "hints": ["price와 count 모두 숫자로 바꿔야 합니다.", "총 금액은 price * count 입니다.", "price = int(input())\ncount = int(input())\nprint(price * count)"],
        "summary": "변수와 입력을 조합하면 쓸모 있는 계산기를 만들 수 있습니다.", "estimatedMinutes": 12,
    },
    {
        "id": "if-first-decision", "order": 16, "level": 2, "unit": "조건문", "title": "조건에 따라 말하기",
        "concept": "if는 조건이 참(True)일 때만, 들여쓴 코드를 실행합니다.",
        "why": "프로그램이 점수나 상태를 보고 서로 다른 행동을 하게 만드는 첫 단계예요.",
        "example": 'score = 75\nif score >= 70:\n    print("통과")', "exampleOutput": "통과",
        "prompt": "score에 75를 저장하고, score가 70 이상이면 “통과”를 출력해 보세요.",
        "starterCode": "score = 75\n# 조건을 작성해 보세요\n", "expectedOutput": "통과",
        "codeRequirements": {"requiredVariableNames": ["score"], "requiredSyntax": ["if"], "requiredOperators": ["greaterOrEqual"]},
        "hints": ["조건문은 if로 시작하고 끝에 :을 붙입니다.", "if 아래에서 실행할 코드는 앞에 공백 4칸을 넣어 들여씁니다.", 'score = 75\nif score >= 70:\n    print("통과")'],
        "summary": "if 조건: 아래에는 공백 4칸 들여쓴 실행 코드가 옵니다.", "estimatedMinutes": 11,
    },
    {
        "id": "temperature-if", "order": 17, "level": 2, "unit": "조건문", "title": "더운 날 알림",
        "concept": ">는 왼쪽 값이 오른쪽 값보다 큰지 비교하는 연산자입니다.",
        "why": "숫자 기준을 정하고 필요한 경우에만 알림을 보여 줄 수 있어요.",
        "example": 'temperature = 32\nif temperature > 30:\n    print("더워요")', "exampleOutput": "더워요",
        "prompt": "temperature에 32를 저장하고, 30보다 크면 “더워요”를 출력해 보세요.",
        "starterCode": "temperature = 32\n# 30보다 큰지 확인해 보세요\n", "expectedOutput": "더워요",
        "codeRequirements": {"requiredVariableNames": ["temperature"], "requiredSyntax": ["if"], "requiredOperators": ["greater"]},
        "hints": ["30보다 크다는 비교는 >로 씁니다.", "if temperature > 30: 처럼 조건 뒤에 :을 붙입니다.", 'temperature = 32\nif temperature > 30:\n    print("더워요")'],
        "summary": "조건식의 결과가 True일 때만 if 블록이 실행됩니다.", "estimatedMinutes": 10,
    },
    {
        "id": "if-else-age", "order": 18, "level": 2, "unit": "조건문", "title": "두 가지 길 만들기",
        "concept": "else는 if의 조건이 거짓(False)일 때 실행할 코드를 정합니다.",
        "why": "하나의 질문에 ‘예’와 ‘아니오’ 모두를 처리할 수 있어요.",
        "example": 'age = 18\nif age >= 19:\n    print("성인")\nelse:\n    print("청소년")', "exampleOutput": "청소년",
        "prompt": "age에 18을 저장하고, 19 이상이면 “성인”, 아니면 “청소년”을 출력해 보세요.",
        "starterCode": "age = 18\n# if와 else를 작성해 보세요\n", "expectedOutput": "청소년",
        "codeRequirements": {"requiredVariableNames": ["age"], "requiredSyntax": ["if"], "requiredOperators": ["greaterOrEqual"], "requiresElse": True},
        "hints": ["if의 조건이 거짓일 때는 else가 실행됩니다.", "else에도 :을 붙이고, 그 아래 코드를 들여씁니다.", 'age = 18\nif age >= 19:\n    print("성인")\nelse:\n    print("청소년")'],
        "summary": "if와 else를 함께 쓰면 모든 경우에 결과를 만들 수 있습니다.", "estimatedMinutes": 12,
    },
    {
        "id": "input-score-result", "order": 19, "level": 2, "unit": "조건문", "title": "입력받은 점수 판정",
        "concept": "입력받은 숫자도 if 조건문에서 비교할 수 있습니다.",
        "why": "사용자마다 다른 결과를 보여 주는 실제 프로그램으로 한 걸음 더 가까워져요.",
        "example": 'score = int(input())\nif score >= 60:\n    print("합격")\nelse:\n    print("다시 도전")', "exampleOutput": "합격",
        "prompt": "점수를 입력받아 60 이상이면 “합격”, 아니면 “다시 도전”을 출력해 보세요. (테스트 입력값: 82)",
        "starterCode": "# 점수를 입력받고 결과를 판정해 보세요\n", "expectedOutput": "합격", "inputs": ["82"],
        "codeRequirements": {"requiredVariableNames": ["score"], "requiredCalls": ["input", "int"], "requiredSyntax": ["if"], "requiredOperators": ["greaterOrEqual"], "requiresElse": True, "testCases": [{"inputs": ["45"], "expectedOutput": "다시 도전"}]},
        "hints": ["점수는 int(input())으로 숫자로 바꿔 받습니다.", "먼저 if score >= 60:을 작성해 보세요.", 'score = int(input())\nif score >= 60:\n    print("합격")\nelse:\n    print("다시 도전")'],
        "summary": "입력 → 비교 → 조건 실행의 흐름이 작은 의사결정 프로그램을 만듭니다.", "estimatedMinutes": 13,
    },
    {
        "id": "odd-even", "order": 20, "level": 2, "unit": "조건문", "title": "홀수와 짝수 구분하기",
        "concept": "%는 나눗셈의 나머지를 구하는 연산자이며, 2로 나눈 나머지가 0이면 짝수입니다.",
        "why": "여러 연산자를 조합해 조건을 만들면 더 구체적인 판단을 할 수 있어요.",
        "example": 'number = int(input())\nif number % 2 == 0:\n    print("짝수")\nelse:\n    print("홀수")', "exampleOutput": "홀수",
        "prompt": "숫자를 입력받아 짝수면 “짝수”, 아니면 “홀수”를 출력해 보세요. (테스트 입력값: 7)",
        "starterCode": "# 2로 나눈 나머지를 이용해 보세요\n", "expectedOutput": "홀수", "inputs": ["7"],
        "codeRequirements": {"requiredVariableNames": ["number"], "requiredCalls": ["input", "int"], "requiredSyntax": ["if"], "requiredOperators": ["modulo", "equal"], "requiresElse": True, "testCases": [{"inputs": ["8"], "expectedOutput": "짝수"}]},
        "hints": ["2로 나눈 나머지는 number % 2로 구합니다.", "나머지가 0과 같은지는 ==로 비교합니다.", 'number = int(input())\nif number % 2 == 0:\n    print("짝수")\nelse:\n    print("홀수")'],
        "summary": "%와 ==를 조합하면 숫자의 특징을 조건으로 만들 수 있습니다.", "estimatedMinutes": 14,
    },
    {
        "id": "study-check-mission", "order": 21, "level": 2, "unit": "미니 미션", "title": "학습 체크인 봇",
        "concept": "문자열도 ==로 비교할 수 있어 조건문에 사용할 수 있습니다.",
        "why": "숫자뿐 아니라 사용자가 입력한 선택에 따라 프로그램의 반응을 바꿀 수 있어요.",
        "example": 'answer = input()\nif answer == "yes":\n    print("오늘의 학습 완료!")\nelse:\n    print("5분만 더 해볼까요?")', "exampleOutput": "오늘의 학습 완료!",
        "prompt": "yes 또는 no를 입력받아, yes면 “오늘의 학습 완료!”, 아니면 “5분만 더 해볼까요?”를 출력해 보세요. (테스트 입력값: yes)",
        "starterCode": "# 나만의 학습 체크인 봇을 만들어 보세요\n", "expectedOutput": "오늘의 학습 완료!", "inputs": ["yes"],
        "codeRequirements": {"requiredVariableNames": ["answer"], "requiredCalls": ["input"], "requiredSyntax": ["if"], "requiredOperators": ["equal"], "requiresElse": True, "testCases": [{"inputs": ["no"], "expectedOutput": "5분만 더 해볼까요?"}]},
        "hints": ["입력값을 answer 변수에 저장해 보세요.", '문자열 yes는 answer == "yes"처럼 비교합니다.', 'answer = input()\nif answer == "yes":\n    print("오늘의 학습 완료!")\nelse:\n    print("5분만 더 해볼까요?")'],
        "summary": "조건문은 입력값에 따라 프로그램의 다음 행동을 선택합니다.", "estimatedMinutes": 14,
    },
    {
        "id": "for-each-language", "order": 22, "level": 3, "unit": "반복문", "title": "목록을 하나씩 읽기",
        "concept": "for는 목록 안의 값을 하나씩 꺼내 같은 작업을 반복합니다.",
        "why": "데이터 분석에서는 한 개의 값보다 많은 데이터를 다루므로 반복의 감각이 중요해요.",
        "example": 'subjects = ["파이썬", "NumPy", "Pandas"]\nfor subject in subjects:\n    print(subject)', "exampleOutput": "파이썬\nNumPy\nPandas",
        "prompt": "subjects 목록의 “파이썬”, “NumPy”, “Pandas”를 for로 한 줄씩 출력해 보세요.",
        "starterCode": "subjects = [\"파이썬\", \"NumPy\", \"Pandas\"]\n# 목록의 값을 하나씩 출력해 보세요\n", "expectedOutput": "파이썬\nNumPy\nPandas",
        "codeRequirements": {"requiredVariableNames": ["subjects"], "requiredSyntax": ["list", "for"]},
        "hints": ["for 변수 in 목록: 형태로 시작합니다.", "for 아래에서 실행할 print()는 공백 4칸 들여씁니다.", 'subjects = ["파이썬", "NumPy", "Pandas"]\nfor subject in subjects:\n    print(subject)'],
        "summary": "for는 목록의 각 값을 순서대로 꺼내 반복합니다.", "estimatedMinutes": 12,
    },
    {
        "id": "range-count", "order": 23, "level": 3, "unit": "반복문", "title": "숫자 범위 반복하기",
        "concept": "range(시작, 끝)은 시작부터 끝 바로 전 숫자까지의 범위를 만듭니다.",
        "why": "횟수가 정해진 작업을 반복할 때 가장 자주 쓰는 방식이에요.",
        "example": "for number in range(1, 4):\n    print(number)", "exampleOutput": "1\n2\n3",
        "prompt": "range(1, 4)를 사용해 1, 2, 3을 한 줄씩 출력해 보세요.",
        "starterCode": "# range()로 1부터 3까지 반복해 보세요\n", "expectedOutput": "1\n2\n3",
        "codeRequirements": {"requiredCalls": ["range"], "requiredSyntax": ["for"]},
        "hints": ["range(1, 4)는 1, 2, 3을 만듭니다.", "끝 숫자 4는 포함되지 않습니다.", "for number in range(1, 4):\n    print(number)"],
        "summary": "range의 끝값은 포함되지 않는다는 점을 기억하세요.", "estimatedMinutes": 11,
    },
    {
        "id": "sum-study-minutes", "order": 24, "level": 3, "unit": "반복문", "title": "학습 시간 더하기",
        "concept": "누적 변수는 반복할 때마다 값을 더해 전체 합계를 만듭니다.",
        "why": "여러 행의 숫자를 합치는 일은 데이터 분석의 가장 기본적인 집계예요.",
        "example": "minutes = [20, 30, 15]\ntotal = 0\nfor minute in minutes:\n    total = total + minute\nprint(total)", "exampleOutput": "65",
        "prompt": "minutes 목록의 값을 모두 더해 total을 출력해 보세요.",
        "starterCode": "minutes = [20, 30, 15]\ntotal = 0\n# 반복하며 total에 더해 보세요\n", "expectedOutput": "65",
        "codeRequirements": {"requiredVariableNames": ["minutes", "total"], "requiredSyntax": ["list", "for"], "requiredOperators": ["add"]},
        "hints": ["합계를 저장할 total을 0으로 시작합니다.", "반복 안에서 total = total + minute처럼 값을 갱신합니다.", "minutes = [20, 30, 15]\ntotal = 0\nfor minute in minutes:\n    total = total + minute\nprint(total)"],
        "summary": "반복문 밖에서 누적 변수를 만들고, 반복문 안에서 갱신합니다.", "estimatedMinutes": 14,
    },
    {
        "id": "filter-passing-scores", "order": 25, "level": 3, "unit": "반복문", "title": "조건에 맞는 점수 찾기",
        "concept": "for 안에 if를 넣으면 여러 값 중 조건에 맞는 값만 골라낼 수 있습니다.",
        "why": "Pandas의 조건 필터링도 같은 생각에서 출발해요.",
        "example": "scores = [85, 60, 92]\nfor score in scores:\n    if score >= 70:\n        print(score)", "exampleOutput": "85\n92",
        "prompt": "scores에서 70 이상인 점수만 한 줄씩 출력해 보세요.",
        "starterCode": "scores = [85, 60, 92]\n# for와 if를 함께 사용해 보세요\n", "expectedOutput": "85\n92",
        "codeRequirements": {"requiredVariableNames": ["scores"], "requiredSyntax": ["list", "for", "if"], "requiredOperators": ["greaterOrEqual"]},
        "hints": ["먼저 scores를 for로 하나씩 꺼냅니다.", "반복문 안에서 if score >= 70: 조건을 작성합니다.", "scores = [85, 60, 92]\nfor score in scores:\n    if score >= 70:\n        print(score)"],
        "summary": "반복 + 조건은 많은 데이터에서 필요한 값만 찾는 기본 패턴입니다.", "estimatedMinutes": 14,
    },
    {
        "id": "count-passing-scores", "order": 26, "level": 3, "unit": "반복문", "title": "조건에 맞는 개수 세기",
        "concept": "조건을 만족할 때마다 count를 1씩 더하면 개수를 셀 수 있습니다.",
        "why": "개수 세기는 데이터의 빈도와 분포를 파악하는 기초가 됩니다.",
        "example": "scores = [85, 60, 92]\ncount = 0\nfor score in scores:\n    if score >= 70:\n        count = count + 1\nprint(count)", "exampleOutput": "2",
        "prompt": "scores에서 70 이상인 점수의 개수를 count에 세어 출력해 보세요.",
        "starterCode": "scores = [85, 60, 92]\ncount = 0\n# 통과 점수를 셀 때마다 count를 1 늘려 보세요\n", "expectedOutput": "2",
        "codeRequirements": {"requiredVariableNames": ["scores", "count"], "requiredSyntax": ["list", "for", "if"], "requiredOperators": ["add", "greaterOrEqual"]},
        "hints": ["조건을 만족했을 때만 count를 바꿉니다.", "1을 더하는 코드는 count = count + 1입니다.", "scores = [85, 60, 92]\ncount = 0\nfor score in scores:\n    if score >= 70:\n        count = count + 1\nprint(count)"],
        "summary": "조건에 맞는 항목 수를 세는 패턴은 분석의 빈도 계산으로 이어집니다.", "estimatedMinutes": 14,
    },
    {
        "id": "average-study-minutes", "order": 27, "level": 3, "unit": "미니 미션", "title": "주간 학습 시간 평균",
        "concept": "합계와 항목 수를 알면 전체 합계를 항목 수로 나누어 평균을 구할 수 있습니다.",
        "why": "NumPy와 Pandas의 mean()도 결국 여러 수의 평균을 구하는 같은 목적을 가집니다.",
        "example": "minutes = [20, 30, 25]\ntotal = 0\nfor minute in minutes:\n    total = total + minute\nprint(total / len(minutes))", "exampleOutput": "25.0",
        "prompt": "minutes의 평균 학습 시간을 출력해 보세요. 반복문으로 total을 만들고 len(minutes)로 항목 수를 구합니다.",
        "starterCode": "minutes = [20, 30, 25]\ntotal = 0\n# 합계를 구한 뒤 평균을 출력해 보세요\n", "expectedOutput": "25.0",
        "codeRequirements": {"requiredVariableNames": ["minutes", "total"], "requiredCalls": ["len"], "requiredSyntax": ["list", "for"], "requiredOperators": ["add", "divide"]},
        "hints": ["먼저 for로 total을 누적합니다.", "len(minutes)는 목록에 들어 있는 항목 수입니다.", "minutes = [20, 30, 25]\ntotal = 0\nfor minute in minutes:\n    total = total + minute\nprint(total / len(minutes))"],
        "summary": "반복으로 직접 만든 평균 계산은 이후 mean()을 이해하는 기반이 됩니다.", "estimatedMinutes": 15,
    },
    {
        "id": "list-index", "order": 28, "level": 4, "unit": "리스트", "title": "목록에서 하나 꺼내기",
        "concept": "리스트는 여러 값을 순서대로 담는 자료구조이며, 인덱스는 0부터 시작합니다.",
        "why": "여러 과목, 여러 점수처럼 같은 종류의 데이터를 한 덩어리로 다룰 수 있어요.",
        "example": 'topics = ["Python", "NumPy", "Pandas"]\nprint(topics[1])', "exampleOutput": "NumPy",
        "prompt": "topics 목록에서 두 번째 값인 “NumPy”를 출력해 보세요.",
        "starterCode": "topics = [\"Python\", \"NumPy\", \"Pandas\"]\n# 두 번째 값을 출력해 보세요\n", "expectedOutput": "NumPy",
        "codeRequirements": {"requiredVariableNames": ["topics"], "requiredSyntax": ["list", "subscript"]},
        "hints": ["리스트의 첫 번째 위치는 0번입니다.", "두 번째 값의 인덱스는 1입니다.", 'topics = ["Python", "NumPy", "Pandas"]\nprint(topics[1])'],
        "summary": "리스트의 인덱스는 0부터 시작합니다.", "estimatedMinutes": 11,
    },
    {
        "id": "list-update", "order": 29, "level": 4, "unit": "리스트", "title": "목록의 값 바꾸기",
        "concept": "리스트는 인덱스를 사용해 특정 위치의 값을 바꿀 수 있습니다.",
        "why": "수정된 점수나 변경된 상태처럼 데이터가 달라질 때 목록을 갱신할 수 있어요.",
        "example": "scores = [70, 80, 90]\nscores[1] = 95\nprint(scores[1])", "exampleOutput": "95",
        "prompt": "scores의 두 번째 값을 95로 바꾸고, 그 값을 출력해 보세요.",
        "starterCode": "scores = [70, 80, 90]\n# 두 번째 값을 95로 바꿔 보세요\n", "expectedOutput": "95",
        "codeRequirements": {"requiredVariableNames": ["scores"], "requiredSyntax": ["list", "subscript"], "requiresSubscriptAssignment": True},
        "hints": ["두 번째 값의 위치는 [1]입니다.", "값을 바꿀 때도 = 기호를 사용합니다.", "scores = [70, 80, 90]\nscores[1] = 95\nprint(scores[1])"],
        "summary": "리스트는 만들어진 뒤에도 원소를 수정할 수 있습니다.", "estimatedMinutes": 12,
    },
    {
        "id": "tuple-point", "order": 30, "level": 4, "unit": "튜플", "title": "변하지 않는 좌표 묶기",
        "concept": "튜플은 여러 값을 순서대로 담지만, 만든 뒤 값을 바꾸지 않는 자료구조입니다.",
        "why": "좌표처럼 한 묶음으로 유지되어야 하는 값을 표현할 때 유용합니다.",
        "example": "point = (3, 4)\nprint(point[0] + point[1])", "exampleOutput": "7",
        "prompt": "point 튜플의 첫 번째와 두 번째 값을 더해 출력해 보세요.",
        "starterCode": "point = (3, 4)\n# 두 좌표 값을 더해 보세요\n", "expectedOutput": "7",
        "codeRequirements": {"requiredVariableNames": ["point"], "requiredSyntax": ["tuple", "subscript"], "requiredOperators": ["add"]},
        "hints": ["튜플도 리스트처럼 [0], [1]로 값을 꺼낼 수 있습니다.", "첫 번째와 두 번째 값을 +로 더합니다.", "point = (3, 4)\nprint(point[0] + point[1])"],
        "summary": "튜플은 순서가 있는, 바꾸지 않을 값의 묶음입니다.", "estimatedMinutes": 11,
    },
    {
        "id": "dictionary-name", "order": 31, "level": 4, "unit": "딕셔너리", "title": "이름표로 값 찾기",
        "concept": "딕셔너리는 키(key)와 값(value)을 짝지어 저장하는 자료구조입니다.",
        "why": "학생의 이름과 점수처럼 ‘무엇의 값인지’가 중요한 데이터를 읽기 쉽게 만듭니다.",
        "example": 'student = {"name": "피터", "score": 88}\nprint(student["name"])', "exampleOutput": "피터",
        "prompt": "student 딕셔너리에서 name에 저장된 “피터”를 출력해 보세요.",
        "starterCode": "student = {\"name\": \"피터\", \"score\": 88}\n# name 값을 출력해 보세요\n", "expectedOutput": "피터",
        "codeRequirements": {"requiredVariableNames": ["student"], "requiredSyntax": ["dict", "subscript"]},
        "hints": ["딕셔너리의 값은 딕셔너리[키]로 꺼냅니다.", "키 name은 문자열이므로 따옴표로 감쌉니다.", 'student = {"name": "피터", "score": 88}\nprint(student["name"])'],
        "summary": "딕셔너리의 키는 값의 의미를 알려 주는 이름표입니다.", "estimatedMinutes": 12,
    },
    {
        "id": "dictionary-profile", "order": 32, "level": 4, "unit": "딕셔너리", "title": "학생 정보 문장 만들기",
        "concept": "딕셔너리의 여러 값을 f 문자열에 넣어 한 사람의 정보를 문장으로 만들 수 있습니다.",
        "why": "행 하나에 여러 속성이 있는 데이터는 이후 Pandas DataFrame의 한 행과 닮아 있습니다.",
        "example": 'student = {"name": "피터", "score": 88}\nprint(f"{student[\'name\']}님의 점수는 {student[\'score\']}점")', "exampleOutput": "피터님의 점수는 88점",
        "prompt": "student의 name과 score를 사용해 “피터님의 점수는 88점”을 출력해 보세요.",
        "starterCode": "student = {\"name\": \"피터\", \"score\": 88}\n# f 문자열로 학생 정보를 출력해 보세요\n", "expectedOutput": "피터님의 점수는 88점",
        "codeRequirements": {"requiredVariableNames": ["student"], "requiredSyntax": ["dict", "subscript", "fString"]},
        "hints": ["f 문자열 앞에 f를 붙입니다.", "딕셔너리 값은 {student['name']}처럼 중괄호 안에 넣습니다.", 'student = {"name": "피터", "score": 88}\nprint(f"{student[\'name\']}님의 점수는 {student[\'score\']}점")'],
        "summary": "딕셔너리의 여러 열을 꺼내면 한 행의 정보를 표현할 수 있습니다.", "estimatedMinutes": 13,
    },
    {
        "id": "student-average-mission", "order": 33, "level": 4, "unit": "미니 미션", "title": "학생 성적 평균 구하기",
        "concept": "딕셔너리 여러 개가 담긴 리스트를 반복하면, 여러 학생의 데이터를 직접 집계할 수 있습니다.",
        "why": "강의의 학생 성적 관리 과제를 시작하는 버전이며, 나중에는 함수와 Pandas로 같은 작업을 확장합니다.",
        "example": "students = [{\"name\": \"민수\", \"score\": 80}, {\"name\": \"영희\", \"score\": 90}]\ntotal = 0\nfor student in students:\n    total = total + student[\"score\"]\nprint(total / len(students))", "exampleOutput": "85.0",
        "prompt": "students의 모든 score를 더해 전체 평균을 출력해 보세요.",
        "starterCode": "students = [{\"name\": \"민수\", \"score\": 80}, {\"name\": \"영희\", \"score\": 90}]\ntotal = 0\n# 모든 학생의 점수를 더한 뒤 평균을 출력해 보세요\n", "expectedOutput": "85.0",
        "codeRequirements": {"requiredVariableNames": ["students", "total"], "requiredCalls": ["len"], "requiredSyntax": ["list", "dict", "subscript", "for"], "requiredOperators": ["add", "divide"]},
        "hints": ["students에서 student를 하나씩 꺼내 반복합니다.", "점수는 student[\"score\"]로 꺼내 total에 더합니다.", "students = [{\"name\": \"민수\", \"score\": 80}, {\"name\": \"영희\", \"score\": 90}]\ntotal = 0\nfor student in students:\n    total = total + student[\"score\"]\nprint(total / len(students))"],
        "summary": "리스트의 딕셔너리를 순회해 집계하는 방식은 표 데이터를 다루는 출발점입니다.", "estimatedMinutes": 16,
    },
    {
        "id": "function-first", "order": 34, "level": 5, "unit": "함수", "title": "반복할 코드에 이름 붙이기",
        "concept": "함수는 여러 줄의 코드를 이름으로 묶어, 필요할 때 다시 실행할 수 있게 합니다.",
        "why": "같은 작업을 여러 번 작성하지 않고 코드의 역할을 분명하게 만들 수 있어요.",
        "example": 'def say_hello():\n    print("안녕하세요")\n\nsay_hello()', "exampleOutput": "안녕하세요",
        "prompt": "say_hello() 함수를 만들고 “안녕하세요”를 출력한 뒤, 함수를 호출해 보세요.",
        "starterCode": "# say_hello 함수를 만들고 호출해 보세요\n", "expectedOutput": "안녕하세요",
        "functionRequirements": {"name": "say_hello", "parameterCount": 0, "parameterNames": [], "testCases": [{"args": [], "expectedOutput": "안녕하세요"}]},
        "hints": ["함수는 def 함수이름(): 으로 시작합니다.", "함수 안의 코드는 공백 4칸 들여씁니다.", 'def say_hello():\n    print("안녕하세요")\n\nsay_hello()'],
        "summary": "def로 함수를 정의하고, 함수이름()으로 실행합니다.", "estimatedMinutes": 13,
    },
    {
        "id": "function-parameter", "order": 35, "level": 5, "unit": "함수", "title": "함수에 값 전달하기",
        "concept": "매개변수(parameter)는 함수를 실행할 때 밖에서 받은 값을 함수 안에서 쓰는 이름입니다. greet(\"피터\")처럼 호출하면, 함수 안의 name에는 \"피터\"가 들어갑니다.",
        "why": "한 함수를 여러 사람, 여러 데이터에 맞게 재사용할 수 있어요.",
        "example": 'def greet(name):\n    print(f"{name}님, 반가워요!")\n\ngreet("피터")', "exampleOutput": "피터님, 반가워요!",
        "prompt": "name 매개변수를 받는 greet 함수를 만드세요. greet(\"피터\")를 호출했을 때 정확히 “피터님, 반가워요!”를 출력해야 합니다.",
        "starterCode": "# name을 받는 greet 함수를 만들어 보세요\n", "expectedOutput": "피터님, 반가워요!",
        "functionRequirements": {"name": "greet", "parameterCount": 1, "parameterNames": ["name"], "testCases": [{"args": ["민수"], "expectedOutput": "민수님, 반가워요!"}]},
        "hints": ["괄호 안에 name을 적으면 매개변수가 됩니다.", "함수 안에서 name은 전달받은 값으로 바뀝니다.", 'def greet(name):\n    print(f"{name}님, 반가워요!")\n\ngreet("피터")'],
        "summary": "매개변수는 함수가 처리할 값을 전달받는 통로입니다.", "estimatedMinutes": 14,
    },
    {
        "id": "function-return", "order": 36, "level": 5, "unit": "함수", "title": "계산 결과 돌려주기",
        "concept": "return은 함수가 만든 결과를 함수 밖으로 돌려주는 명령입니다.",
        "why": "출력만 하는 대신 계산 결과를 다른 계산이나 변수에 다시 사용할 수 있어요.",
        "example": "def add(first, second):\n    return first + second\n\nprint(add(12, 8))", "exampleOutput": "20",
        "prompt": "두 수를 더해 돌려주는 add 함수를 만들고, add(12, 8)의 결과를 출력해 보세요.",
        "starterCode": "# add 함수를 만들어 보세요\n", "expectedOutput": "20",
        "functionRequirements": {"name": "add", "parameterCount": 2, "parameterNames": ["first", "second"], "requiresReturn": True, "testCases": [{"args": [3, 5], "expectedReturn": 8}]},
        "hints": ["함수 결과는 return 뒤에 씁니다.", "add 안에서는 first + second를 return합니다.", "def add(first, second):\n    return first + second\n\nprint(add(12, 8))"],
        "summary": "return 값은 함수 호출 자리에 결과로 들어갑니다.", "estimatedMinutes": 14,
    },
    {
        "id": "function-count-pass", "order": 37, "level": 5, "unit": "함수", "title": "통과 점수 세기 함수",
        "concept": "함수 안에서도 반복문과 조건문을 조합해 하나의 작업으로 만들 수 있습니다.",
        "why": "데이터를 세는 규칙을 함수로 만들면 다른 점수 목록에도 재사용할 수 있어요.",
        "example": "def count_passing(scores):\n    count = 0\n    for score in scores:\n        if score >= 70:\n            count = count + 1\n    return count\n\nprint(count_passing([85, 60, 92]))", "exampleOutput": "2",
        "prompt": "scores = [85, 60, 92]에서 70점 이상인 점수의 개수를 돌려주는 count_passing 함수를 만드세요. count_passing(scores)의 결과 2를 출력해야 합니다.",
        "starterCode": "scores = [85, 60, 92]\n# count_passing 함수를 만든 뒤 결과를 출력해 보세요\n", "expectedOutput": "2",
        "functionRequirements": {"name": "count_passing", "parameterCount": 1, "parameterNames": ["scores"], "requiresReturn": True, "requiresFor": True, "requiresIf": True, "testCases": [{"args": [[70, 69, 80, 90]], "expectedReturn": 3}]},
        "hints": ["함수 안에서 count를 0으로 시작합니다.", "반복과 조건문이 끝난 뒤 count를 return합니다.", "def count_passing(scores):\n    count = 0\n    for score in scores:\n        if score >= 70:\n            count = count + 1\n    return count\n\nprint(count_passing([85, 60, 92]))"],
        "summary": "함수는 반복·조건 규칙을 이름 있는 작업으로 묶습니다.", "estimatedMinutes": 17,
    },
    {
        "id": "function-average", "order": 38, "level": 5, "unit": "함수", "title": "평균 계산 함수",
        "concept": "목록을 매개변수로 받으면, 목록이 달라져도 같은 계산 규칙을 적용할 수 있습니다.",
        "why": "Pandas의 mean()처럼 데이터를 넣으면 결과를 돌려주는 도구를 직접 만드는 경험이에요.",
        "example": "def calculate_average(scores):\n    total = 0\n    for score in scores:\n        total = total + score\n    return total / len(scores)\n\nprint(calculate_average([80, 90]))", "exampleOutput": "85.0",
        "prompt": "scores = [80, 90]의 평균을 돌려주는 calculate_average 함수를 만드세요. calculate_average(scores)의 결과 85.0을 출력해야 합니다.",
        "starterCode": "scores = [80, 90]\n# calculate_average 함수를 만든 뒤 결과를 출력해 보세요\n", "expectedOutput": "85.0",
        "functionRequirements": {"name": "calculate_average", "parameterCount": 1, "parameterNames": ["scores"], "requiresReturn": True, "requiresFor": True, "testCases": [{"args": [[60, 80, 100]], "expectedReturn": 80.0}]},
        "hints": ["함수 안에서 total을 0으로 만들고 점수를 더합니다.", "합계를 len(scores)로 나눈 값을 return합니다.", "def calculate_average(scores):\n    total = 0\n    for score in scores:\n        total = total + score\n    return total / len(scores)\n\nprint(calculate_average([80, 90]))"],
        "summary": "함수에 목록을 전달하면 같은 분석 규칙을 여러 데이터에 적용할 수 있습니다.", "estimatedMinutes": 18,
    },
    {
        "id": "student-average-function-mission", "order": 39, "level": 5, "unit": "미니 미션", "title": "학생 성적 분석 함수",
        "concept": "리스트 안의 딕셔너리를 함수로 전달하면, 여러 학생의 정보를 한 번에 분석할 수 있습니다.",
        "why": "강의의 학생 성적 관리 과제에서 함수가 왜 필요한지 체감하는 첫 단계입니다.",
        "example": "def calculate_student_average(students):\n    total = 0\n    for student in students:\n        total = total + student[\"score\"]\n    return total / len(students)\n\nstudents = [{\"name\": \"민수\", \"score\": 80}, {\"name\": \"영희\", \"score\": 90}]\nprint(calculate_student_average(students))", "exampleOutput": "85.0",
        "prompt": "여러 학생의 score 평균을 돌려주는 calculate_student_average 함수를 완성해 보세요.",
        "starterCode": "students = [{\"name\": \"민수\", \"score\": 80}, {\"name\": \"영희\", \"score\": 90}]\n# 학생 성적 평균 함수를 만든 뒤 결과를 출력해 보세요\n", "expectedOutput": "85.0",
        "functionRequirements": {"name": "calculate_student_average", "parameterCount": 1, "parameterNames": ["students"], "requiresReturn": True, "requiresFor": True, "testCases": [{"args": [[{"name": "가", "score": 60}, {"name": "나", "score": 100}, {"name": "다", "score": 95}]], "expectedReturn": 85.0}]},
        "hints": ["함수는 students 목록을 매개변수로 받습니다.", "반복문에서 student[\"score\"]를 total에 더합니다.", "def calculate_student_average(students):\n    total = 0\n    for student in students:\n        total = total + student[\"score\"]\n    return total / len(students)\n\nstudents = [{\"name\": \"민수\", \"score\": 80}, {\"name\": \"영희\", \"score\": 90}]\nprint(calculate_student_average(students))"],
        "summary": "함수는 복잡해진 데이터 처리 과정을 재사용 가능한 이름으로 정리합니다.", "estimatedMinutes": 20,
    },
    # Level 6: function design. Hidden tests confirm the function works for values
    # that are different from the values shown in the question.
    {
        "id": "function-boolean", "order": 40, "level": 6, "unit": "함수 설계", "title": "통과 여부를 돌려주는 함수",
        "concept": "비교식의 결과는 True 또는 False입니다. 함수를 사용하면 이 판단 규칙을 여러 점수에 다시 적용할 수 있습니다.",
        "why": "조건문을 여러 곳에 복사하지 않고, ‘통과 판단’이라는 역할에 이름을 붙일 수 있어요.",
        "example": "def is_passing(score):\n    return score >= 70\n\nprint(is_passing(85))", "exampleOutput": "True",
        "prompt": "score가 70 이상이면 True, 아니면 False를 돌려주는 is_passing(score) 함수를 만들고 is_passing(85)의 결과를 출력해 보세요.",
        "starterCode": "# is_passing 함수를 만든 뒤 결과를 출력해 보세요\n", "expectedOutput": "True",
        "functionRequirements": {"name": "is_passing", "parameterCount": 1, "parameterNames": ["score"], "requiresReturn": True, "testCases": [{"args": [69], "expectedReturn": False}, {"args": [70], "expectedReturn": True}]},
        "hints": ["함수의 결과는 score >= 70 비교식 자체가 될 수 있어요.", "print는 함수 밖에서 하고, 함수 안에서는 비교 결과를 return합니다.", "def is_passing(score):\n    return score >= 70\n\nprint(is_passing(85))"],
        "summary": "비교식의 True·False 결과도 함수의 반환값으로 만들 수 있습니다.", "estimatedMinutes": 14,
    },
    {
        "id": "function-default", "order": 41, "level": 6, "unit": "함수 설계", "title": "기본 인사가 있는 함수",
        "concept": "기본값(default)은 호출할 때 값을 생략했을 때 사용하는 미리 정한 값입니다.",
        "why": "대부분 같은 값을 쓰되, 필요할 때만 바꾸는 함수는 호출하기가 더 간단해져요.",
        "example": "def greet(name, greeting=\"안녕하세요\"):\n    print(f\"{greeting}, {name}님!\")\n\ngreet(\"피터\")", "exampleOutput": "안녕하세요, 피터님!",
        "prompt": "greet(name, greeting=\"안녕하세요\") 함수를 만드세요. greet(\"피터\")를 호출하면 “안녕하세요, 피터님!”을 출력해야 합니다.",
        "starterCode": "# greeting의 기본값을 가진 greet 함수를 만들어 보세요\n", "expectedOutput": "안녕하세요, 피터님!",
        "functionRequirements": {"name": "greet", "parameterCount": 2, "parameterNames": ["name", "greeting"], "defaultValues": ["안녕하세요"], "testCases": [{"args": ["민수"], "expectedOutput": "안녕하세요, 민수님!"}]},
        "hints": ["기본값은 매개변수 이름 뒤에 =로 붙입니다.", "name과 greeting 모두 f 문자열 안에 넣어 문장을 만듭니다.", "def greet(name, greeting=\"안녕하세요\"):\n    print(f\"{greeting}, {name}님!\")\n\ngreet(\"피터\")"],
        "summary": "기본값을 쓰면 자주 쓰는 인자를 생략할 수 있습니다.", "estimatedMinutes": 15,
    },
    {
        "id": "function-annotation", "order": 42, "level": 6, "unit": "함수 설계", "title": "함수 사용 설명서 붙이기",
        "concept": "자료형 힌트(type hint)는 함수가 어떤 값을 받고 어떤 값을 돌려주는지 알려 주는 메모입니다.",
        "why": "함수를 나중에 다시 읽거나 다른 사람과 함께 쓸 때, 값의 종류를 빠르게 파악할 수 있어요.",
        "example": "def format_score(name: str, score: int) -> str:\n    return f\"{name}: {score}점\"\n\nprint(format_score(\"피터\", 85))", "exampleOutput": "피터: 85점",
        "prompt": "name: str, score: int를 받고 str을 돌려주는 format_score 함수를 만드세요. format_score(\"피터\", 85)의 결과를 출력해 보세요.",
        "starterCode": "# 자료형 힌트가 있는 format_score 함수를 만들어 보세요\n", "expectedOutput": "피터: 85점",
        "functionRequirements": {"name": "format_score", "parameterCount": 2, "parameterNames": ["name", "score"], "requiresReturn": True, "requiresAnnotations": True, "testCases": [{"args": ["민수", 92], "expectedReturn": "민수: 92점"}]},
        "hints": ["매개변수 이름 뒤에는 : str 또는 : int를 붙입니다.", "괄호 뒤의 -> str은 반환값이 문자열임을 알려 줍니다.", "def format_score(name: str, score: int) -> str:\n    return f\"{name}: {score}점\"\n\nprint(format_score(\"피터\", 85))"],
        "summary": "자료형 힌트는 실행 규칙이 아니라 함수의 사용 설명서 역할을 합니다.", "estimatedMinutes": 16,
    },
    {
        "id": "function-best-score", "order": 43, "level": 6, "unit": "함수 설계", "title": "가장 높은 점수 찾기",
        "concept": "함수 안에서도 반복하면서 현재까지의 가장 큰 값을 기억할 수 있습니다.",
        "why": "목록 길이와 값이 달라져도 같은 규칙으로 최고 점수를 찾을 수 있어요.",
        "example": "def find_best_score(scores):\n    best = scores[0]\n    for score in scores:\n        if score > best:\n            best = score\n    return best\n\nprint(find_best_score([70, 92, 81]))", "exampleOutput": "92",
        "prompt": "점수 목록에서 가장 큰 값을 돌려주는 find_best_score(scores) 함수를 만들고 [70, 92, 81]의 결과를 출력해 보세요.",
        "starterCode": "scores = [70, 92, 81]\n# find_best_score 함수를 만든 뒤 결과를 출력해 보세요\n", "expectedOutput": "92",
        "functionRequirements": {"name": "find_best_score", "parameterCount": 1, "parameterNames": ["scores"], "requiresReturn": True, "requiresFor": True, "requiresIf": True, "testCases": [{"args": [[55, 100, 73]], "expectedReturn": 100}]},
        "hints": ["첫 번째 점수를 임시 최고 점수 best로 저장합니다.", "반복 중 score가 best보다 클 때만 best를 바꿉니다.", "def find_best_score(scores):\n    best = scores[0]\n    for score in scores:\n        if score > best:\n            best = score\n    return best\n\nprint(find_best_score([70, 92, 81]))"],
        "summary": "현재까지의 결과를 변수에 기억하며 목록을 훑는 패턴입니다.", "estimatedMinutes": 18,
    },
    {
        "id": "function-empty-average", "order": 44, "level": 6, "unit": "함수 설계", "title": "빈 목록도 안전한 평균",
        "concept": "나누기 전에 목록이 비어 있는지 확인하면 0으로 나누는 오류를 피할 수 있습니다.",
        "why": "현실의 데이터는 비어 있을 수 있으므로, 예외적인 경우를 먼저 정하는 습관이 필요해요.",
        "example": "def safe_average(scores):\n    if not scores:\n        return 0\n    total = 0\n    for score in scores:\n        total += score\n    return total / len(scores)\n\nprint(safe_average([]))", "exampleOutput": "0",
        "prompt": "scores가 비어 있으면 0을, 값이 있으면 평균을 돌려주는 safe_average(scores) 함수를 만들고 safe_average([])를 출력해 보세요.",
        "starterCode": "# 빈 목록부터 처리하는 safe_average 함수를 만들어 보세요\n", "expectedOutput": "0",
        "functionRequirements": {"name": "safe_average", "parameterCount": 1, "parameterNames": ["scores"], "requiresReturn": True, "requiresFor": True, "requiresIf": True, "testCases": [{"args": [[60, 80, 100]], "expectedReturn": 80.0}, {"args": [[]], "expectedReturn": 0}]},
        "hints": ["빈 리스트는 if not scores:로 확인할 수 있습니다.", "빈 경우에는 바로 return하고, 그 아래에서 일반 평균을 계산합니다.", "def safe_average(scores):\n    if not scores:\n        return 0\n    total = 0\n    for score in scores:\n        total += score\n    return total / len(scores)\n\nprint(safe_average([]))"],
        "summary": "예외적인 입력을 먼저 처리하면 나머지 계산이 단순해집니다.", "estimatedMinutes": 19,
    },
    {
        "id": "function-profile-dict", "order": 45, "level": 6, "unit": "함수 설계", "title": "정보를 딕셔너리로 돌려주기",
        "concept": "함수의 반환값은 숫자나 문자열뿐 아니라 여러 정보를 담은 딕셔너리도 될 수 있습니다.",
        "why": "관련 있는 값을 하나의 결과로 묶어 두면 다음 코드에서 이름표로 꺼내 쓰기 편합니다.",
        "example": "def create_profile(name, score):\n    return {\"name\": name, \"score\": score}\n\nprint(create_profile(\"피터\", 85)[\"score\"])", "exampleOutput": "85",
        "prompt": "name과 score를 받아 {\"name\": ..., \"score\": ...} 딕셔너리를 돌려주는 create_profile 함수를 만들고, 피터의 score를 출력해 보세요.",
        "starterCode": "# create_profile 함수를 만든 뒤 score를 출력해 보세요\n", "expectedOutput": "85",
        "functionRequirements": {"name": "create_profile", "parameterCount": 2, "parameterNames": ["name", "score"], "requiresReturn": True, "testCases": [{"args": ["민수", 90], "expectedReturn": {"name": "민수", "score": 90}}]},
        "hints": ["return 뒤에 키와 값을 가진 딕셔너리를 만듭니다.", "딕셔너리의 값 자리에는 따옴표가 아닌 매개변수 name, score를 넣습니다.", "def create_profile(name, score):\n    return {\"name\": name, \"score\": score}\n\nprint(create_profile(\"피터\", 85)[\"score\"])"],
        "summary": "함수는 여러 값을 딕셔너리 하나로 묶어 반환할 수 있습니다.", "estimatedMinutes": 16,
    },
    {
        "id": "function-greeting-builder", "order": 46, "level": 6, "unit": "함수 설계", "title": "인사 문장을 만들어 돌려주기",
        "concept": "문장을 화면에 바로 출력하지 않고 return하면, 다른 함수나 print에서 다시 사용할 수 있습니다.",
        "why": "출력과 문장 만들기를 나누면 함수의 역할이 더 명확해집니다.",
        "example": "def build_greeting(name):\n    return f\"{name}님, 오늘도 화이팅!\"\n\nmessage = build_greeting(\"피터\")\nprint(message)", "exampleOutput": "피터님, 오늘도 화이팅!",
        "prompt": "이름을 받아 “이름님, 오늘도 화이팅!” 문장을 돌려주는 build_greeting(name) 함수를 만들고 피터의 문장을 출력해 보세요.",
        "starterCode": "# build_greeting 함수를 만든 뒤 반환값을 출력해 보세요\n", "expectedOutput": "피터님, 오늘도 화이팅!",
        "functionRequirements": {"name": "build_greeting", "parameterCount": 1, "parameterNames": ["name"], "requiresReturn": True, "testCases": [{"args": ["민수"], "expectedReturn": "민수님, 오늘도 화이팅!"}]},
        "hints": ["문장 만들기는 return, 화면 출력은 함수 밖의 print로 나눕니다.", "f 문자열의 {name} 자리에 전달받은 이름이 들어갑니다.", "def build_greeting(name):\n    return f\"{name}님, 오늘도 화이팅!\"\n\nmessage = build_greeting(\"피터\")\nprint(message)"],
        "summary": "return하는 함수는 만든 결과를 여러 곳에서 조합할 수 있습니다.", "estimatedMinutes": 15,
    },
    {
        "id": "function-report-mission", "order": 47, "level": 6, "unit": "미니 미션", "title": "점수 한 줄 보고서 만들기",
        "concept": "함수 안에서 평균·조건·문자열 조합을 순서대로 처리하면 하나의 작은 보고서를 만들 수 있습니다.",
        "why": "여러 문법을 한 번에 조합하되, 함수의 입력과 반환값을 먼저 정하면 길을 잃지 않아요.",
        "example": "def make_report(name, scores):\n    total = 0\n    for score in scores:\n        total += score\n    average = total / len(scores)\n    if average >= 70:\n        return f\"{name}: 통과\"\n    return f\"{name}: 재도전\"\n\nprint(make_report(\"피터\", [80, 90]))", "exampleOutput": "피터: 통과",
        "prompt": "이름과 점수 목록을 받아 평균이 70 이상이면 “이름: 통과”, 아니면 “이름: 재도전”을 돌려주는 make_report 함수를 만들고 피터의 결과를 출력해 보세요.",
        "starterCode": "# make_report 함수를 만든 뒤 피터의 결과를 출력해 보세요\n", "expectedOutput": "피터: 통과",
        "functionRequirements": {"name": "make_report", "parameterCount": 2, "parameterNames": ["name", "scores"], "requiresReturn": True, "requiresFor": True, "requiresIf": True, "testCases": [{"args": ["민수", [50, 60]], "expectedReturn": "민수: 재도전"}]},
        "hints": ["먼저 scores의 합계를 만든 뒤 len(scores)로 나눠 average를 구합니다.", "average >= 70의 참·거짓에 따라 서로 다른 f 문자열을 return합니다.", "def make_report(name, scores):\n    total = 0\n    for score in scores:\n        total += score\n    average = total / len(scores)\n    if average >= 70:\n        return f\"{name}: 통과\"\n    return f\"{name}: 재도전\"\n\nprint(make_report(\"피터\", [80, 90]))"],
        "summary": "함수 하나에 작은 분석 규칙을 담아 재사용 가능한 보고서를 만듭니다.", "estimatedMinutes": 22,
    },
    # Level 7: loops that stop safely, input errors, and a small standard library.
    {
        "id": "while-count", "order": 48, "level": 7, "unit": "안전한 입력", "title": "while로 1부터 세기",
        "concept": "while문은 조건이 참인 동안 같은 일을 반복합니다. 반복 안에서 값이 변해야 언젠가 조건이 거짓이 됩니다.",
        "why": "반복 횟수를 미리 알기 어려운 입력·게임·검증 상황에서 for문과 다른 방식으로 활용합니다.",
        "example": "number = 1\nwhile number <= 3:\n    print(number)\n    number += 1", "exampleOutput": "1\n2\n3",
        "prompt": "number를 1에서 시작해 while문으로 1, 2, 3을 한 줄씩 출력해 보세요.",
        "starterCode": "number = 1\n# while문으로 3까지 출력해 보세요\n", "expectedOutput": "1\n2\n3",
        "codeRequirements": {"requiredVariableNames": ["number"], "requiredSyntax": ["while"]},
        "hints": ["조건에는 number <= 3처럼 반복을 계속할 기준을 씁니다.", "반복문 안에서 number를 1씩 늘려야 반복이 끝납니다.", "number = 1\nwhile number <= 3:\n    print(number)\n    number += 1"],
        "summary": "while문에는 계속할 조건과 조건을 바꾸는 코드가 함께 필요합니다.", "estimatedMinutes": 14,
    },
    {
        "id": "while-until-quit", "order": 49, "level": 7, "unit": "안전한 입력", "title": "종료 글자까지 반복하기",
        "concept": "반복을 시작하기 전에도 입력을 한 번 받고, 반복 끝에서 다음 입력을 받으면 종료 조건을 자연스럽게 확인할 수 있습니다.",
        "why": "사용자가 q를 입력할 때까지 계속하는 메뉴·게임 같은 프로그램의 기본 구조예요.",
        "example": "answer = input()\nwhile answer != \"q\":\n    print(\"계속\")\n    answer = input()\nprint(\"종료\")", "exampleOutput": "계속\n종료",
        "prompt": "사용자가 q를 입력할 때까지 “계속”을 출력하고, q를 입력하면 “종료”를 출력해 보세요. 이 레슨의 입력은 hello 다음 q입니다.",
        "starterCode": "# 먼저 입력을 받고, q가 아닐 동안 반복해 보세요\n", "expectedOutput": "계속\n종료", "inputs": ["hello", "q"],
        "codeRequirements": {"requiredVariableNames": ["answer"], "requiredCalls": ["input"], "minimumCallCounts": {"input": 2}, "requiredSyntax": ["while"]},
        "hints": ["첫 input() 결과를 answer에 저장한 뒤 while 조건에서 q와 비교합니다.", "반복문 안의 마지막에서 answer를 다시 입력받아야 다음 조건을 확인할 수 있습니다.", "answer = input()\nwhile answer != \"q\":\n    print(\"계속\")\n    answer = input()\nprint(\"종료\")"],
        "summary": "while문은 ‘언제 멈출지’를 조건으로 표현할 때 편리합니다.", "estimatedMinutes": 17,
    },
    {
        "id": "try-number", "order": 50, "level": 7, "unit": "안전한 입력", "title": "숫자가 아닐 때 안내하기",
        "concept": "try에는 실행해 볼 코드를, except에는 오류가 났을 때의 대처를 적습니다.",
        "why": "사람이 입력하는 프로그램에서는 예상하지 못한 글자가 들어와도 멈추지 않도록 안내할 수 있어요.",
        "example": "try:\n    number = int(input())\n    print(number + 1)\nexcept ValueError:\n    print(\"숫자를 입력해 주세요\")", "exampleOutput": "9",
        "prompt": "입력한 숫자에 1을 더해 출력하되, 숫자가 아니면 “숫자를 입력해 주세요”를 출력해 보세요. 이 레슨의 입력은 8입니다.",
        "starterCode": "# int(input())을 try에서 실행하고 ValueError를 처리해 보세요\n", "expectedOutput": "9", "inputs": ["8"],
        "codeRequirements": {"requiredCalls": ["input", "int"], "requiredSyntax": ["try"], "testCases": [{"inputs": ["hello"], "expectedOutput": "숫자를 입력해 주세요"}]},
        "hints": ["int(input())이 실패할 수 있는 코드를 try 아래에 들여씁니다.", "except ValueError: 아래에 안내 문장을 출력합니다.", "try:\n    number = int(input())\n    print(number + 1)\nexcept ValueError:\n    print(\"숫자를 입력해 주세요\")"],
        "summary": "try/except는 오류를 숨기는 것이 아니라, 사용자에게 다음 행동을 알려 주는 방법입니다.", "estimatedMinutes": 18,
    },
    {
        "id": "score-range", "order": 51, "level": 7, "unit": "안전한 입력", "title": "점수 범위 확인하기",
        "concept": "조건문을 한 번 더 쓰면 숫자인지뿐 아니라 값의 범위도 확인할 수 있습니다.",
        "why": "점수처럼 허용 범위가 있는 데이터는 저장하거나 계산하기 전에 검증하는 습관이 중요해요.",
        "example": "score = int(input())\nif 0 <= score and score <= 100:\n    print(\"저장 완료\")\nelse:\n    print(\"0부터 100 사이를 입력해 주세요\")", "exampleOutput": "저장 완료",
        "prompt": "입력한 score가 0 이상 100 이하면 “저장 완료”, 아니면 “0부터 100 사이를 입력해 주세요”를 출력해 보세요. 입력은 85입니다.",
        "starterCode": "# score의 범위를 확인하는 if문을 작성해 보세요\n", "expectedOutput": "저장 완료", "inputs": ["85"],
        "codeRequirements": {"requiredVariableNames": ["score"], "requiredCalls": ["input", "int"], "requiredSyntax": ["if"], "requiresElse": True, "testCases": [{"inputs": ["120"], "expectedOutput": "0부터 100 사이를 입력해 주세요"}]},
        "hints": ["0 <= score와 score <= 100 두 조건이 모두 참이어야 합니다.", "두 조건을 and로 연결하고, 조건이 거짓일 때는 else에서 안내합니다.", "score = int(input())\nif 0 <= score and score <= 100:\n    print(\"저장 완료\")\nelse:\n    print(\"0부터 100 사이를 입력해 주세요\")"],
        "summary": "입력값을 받은 뒤 범위를 확인하면 잘못된 데이터가 다음 계산으로 넘어가지 않습니다.", "estimatedMinutes": 17,
    },
    {
        "id": "random-choice", "order": 52, "level": 7, "unit": "표준 라이브러리", "title": "목록에서 무작위로 고르기",
        "concept": "random 모듈의 choice()는 목록 안에서 하나를 무작위로 골라 줍니다.",
        "why": "퀴즈 문제, 가위바위보 상대 선택처럼 매번 다른 결과가 필요한 프로그램에 쓸 수 있어요.",
        "example": "import random\nchoices = [\"가위\", \"바위\", \"보\"]\nprint(random.choice(choices))", "exampleOutput": "가위 또는 바위 또는 보",
        "prompt": "random 모듈을 불러오고 choices 목록에서 random.choice()로 하나를 골라 출력해 보세요.",
        "starterCode": "choices = [\"가위\", \"바위\", \"보\"]\n# random 모듈을 불러와 하나를 골라 보세요\n", "expectedOutput": "", "checkType": "non_empty_output",
        "codeRequirements": {"requiredVariableNames": ["choices"], "requiredSyntax": ["list", "import"], "requiredImports": ["random"], "requiredAttributeCalls": ["choice"]},
        "hints": ["파일 맨 위에 import random을 적습니다.", "모듈의 기능은 random.choice(목록)처럼 점으로 연결합니다.", "import random\nchoices = [\"가위\", \"바위\", \"보\"]\nprint(random.choice(choices))"],
        "summary": "import는 다른 모듈에 준비된 기능을 현재 코드에서 쓰게 해 줍니다.", "estimatedMinutes": 14,
    },
    {
        "id": "math-ceil", "order": 53, "level": 7, "unit": "표준 라이브러리", "title": "필요한 기능만 가져오기",
        "concept": "from 모듈 import 기능 형태를 쓰면 그 기능 이름을 바로 사용할 수 있습니다.",
        "why": "모듈 전체가 아니라 필요한 기능이 무엇인지 코드에서 더 분명하게 보여 줄 수 있어요.",
        "example": "from math import ceil\nprint(ceil(3.2))", "exampleOutput": "4",
        "prompt": "math 모듈에서 ceil을 가져와 3.2를 올림한 결과를 출력해 보세요.",
        "starterCode": "# math에서 ceil을 가져온 뒤 3.2에 사용해 보세요\n", "expectedOutput": "4",
        "codeRequirements": {"requiredCalls": ["ceil"], "requiredSyntax": ["importFrom"], "requiredImports": ["math"]},
        "hints": ["from math import ceil로 필요한 기능만 가져옵니다.", "가져온 뒤에는 math.ceil이 아니라 ceil(3.2)처럼 씁니다.", "from math import ceil\nprint(ceil(3.2))"],
        "summary": "from ... import ...는 필요한 기능을 현재 이름 공간으로 가져옵니다.", "estimatedMinutes": 13,
    },
    {
        "id": "date-object", "order": 54, "level": 7, "unit": "표준 라이브러리", "title": "날짜 객체에서 연도 꺼내기",
        "concept": "datetime 모듈의 date는 연·월·일을 하나의 날짜 객체로 묶어 표현합니다.",
        "why": "문자열로 날짜를 직접 나누는 대신, 날짜의 year 같은 정보를 안전하게 꺼낼 수 있어요.",
        "example": "from datetime import date\nstudy_day = date(2026, 9, 3)\nprint(study_day.year)", "exampleOutput": "2026",
        "prompt": "datetime에서 date를 가져오고 2026년 9월 3일 날짜를 만든 뒤, year를 출력해 보세요.",
        "starterCode": "# date를 가져와 study_day를 만든 뒤 year를 출력해 보세요\n", "expectedOutput": "2026",
        "codeRequirements": {"requiredVariableNames": ["study_day"], "requiredCalls": ["date"], "requiredSyntax": ["importFrom"], "requiredImports": ["datetime"]},
        "hints": ["from datetime import date로 date를 가져옵니다.", "date(연도, 월, 일)로 만든 뒤 .year로 연도를 꺼냅니다.", "from datetime import date\nstudy_day = date(2026, 9, 3)\nprint(study_day.year)"],
        "summary": "객체의 .year처럼 점 뒤의 이름은 그 객체가 가진 정보나 기능입니다.", "estimatedMinutes": 15,
    },
    {
        "id": "safe-order-mission", "order": 55, "level": 7, "unit": "미니 미션", "title": "안전한 주문 수량 받기",
        "concept": "try/except와 범위 조건을 함께 쓰면 글자 입력과 잘못된 숫자 입력을 모두 구분할 수 있습니다.",
        "why": "입력을 믿고 바로 계산하기보다, 확인한 뒤 계산하는 습관은 실제 서비스에서도 중요합니다.",
        "example": "try:\n    count = int(input())\n    if count < 1:\n        print(\"1 이상 입력\")\n    else:\n        print(count * 1000)\nexcept ValueError:\n    print(\"숫자를 입력\")", "exampleOutput": "1 이상 입력",
        "prompt": "주문 수량 count를 입력받아 1 미만이면 “1 이상 입력”, 1 이상이면 1000을 곱한 금액을 출력하세요. 글자를 입력하면 “숫자를 입력”을 출력해야 합니다. 입력은 0입니다.",
        "starterCode": "# 숫자 변환, 범위 확인, 오류 처리를 순서대로 작성해 보세요\n", "expectedOutput": "1 이상 입력", "inputs": ["0"],
        "codeRequirements": {"requiredVariableNames": ["count"], "requiredCalls": ["input", "int"], "requiredSyntax": ["try", "if"], "requiresElse": True, "testCases": [{"inputs": ["3"], "expectedOutput": "3000"}, {"inputs": ["abc"], "expectedOutput": "숫자를 입력"}]},
        "hints": ["int(input())을 try 안에서 실행하고, 변환된 count를 if로 확인합니다.", "글자 입력은 ValueError가 나므로 except에서 별도 문장을 출력합니다.", "try:\n    count = int(input())\n    if count < 1:\n        print(\"1 이상 입력\")\n    else:\n        print(count * 1000)\nexcept ValueError:\n    print(\"숫자를 입력\")"],
        "summary": "안전한 입력 처리는 변환 오류와 값 범위를 각각 확인합니다.", "estimatedMinutes": 22,
    },
    # Level 8: objects remember values in self, and methods use those values.
    {
        "id": "class-student-intro", "order": 56, "level": 8, "unit": "클래스", "title": "학생 객체 만들기",
        "concept": "클래스는 같은 종류의 데이터를 만들기 위한 설계도이고, 객체는 설계도로 만든 실제 한 개의 값입니다.",
        "why": "학생마다 이름을 따로 기억하면서 같은 소개 기능을 쓰게 만들 수 있어요.",
        "example": "class Student:\n    def __init__(self, name):\n        self.name = name\n\n    def introduce(self):\n        print(f\"저는 {self.name}입니다.\")\n\nstudent = Student(\"피터\")\nstudent.introduce()", "exampleOutput": "저는 피터입니다.",
        "prompt": "name을 받는 Student 클래스를 만들고, introduce()가 “저는 이름입니다.”를 출력하게 하세요. Student(\"피터\")의 소개를 출력해 보세요.",
        "starterCode": "# Student 클래스와 introduce 메서드를 만들어 보세요\n", "expectedOutput": "저는 피터입니다.",
        "classRequirements": {"name": "Student", "initParameterNames": ["name"], "requiredMethods": ["introduce"], "requiredAttributes": ["name"], "testCases": [{"constructorArgs": ["민수"], "method": "introduce", "expectedOutput": "저는 민수입니다."}]},
        "hints": ["__init__은 객체를 만들 때 한 번 실행되고, self.name에 이름을 저장합니다.", "메서드의 첫 번째 매개변수 self는 ‘이 객체 자신’을 뜻합니다.", "class Student:\n    def __init__(self, name):\n        self.name = name\n\n    def introduce(self):\n        print(f\"저는 {self.name}입니다.\")\n\nstudent = Student(\"피터\")\nstudent.introduce()"],
        "summary": "객체는 self.속성에 자기만의 값을 기억합니다.", "estimatedMinutes": 20,
    },
    {
        "id": "class-student-pass", "order": 57, "level": 8, "unit": "클래스", "title": "객체의 점수로 통과 판단하기",
        "concept": "메서드는 매개변수로 받은 값뿐 아니라 self에 저장한 속성을 사용할 수 있습니다.",
        "why": "학생의 이름·점수처럼 서로 관련된 값과 행동을 한 객체 안에 모을 수 있어요.",
        "example": "class Student:\n    def __init__(self, name, score):\n        self.name = name\n        self.score = score\n\n    def is_passing(self):\n        return self.score >= 70\n\nprint(Student(\"피터\", 85).is_passing())", "exampleOutput": "True",
        "prompt": "name과 score를 저장하는 Student 클래스를 만들고, is_passing()이 self.score로 70점 이상 여부를 돌려주게 하세요. 피터 85점의 결과를 출력해 보세요.",
        "starterCode": "# score를 기억하고 is_passing으로 판단하는 Student 클래스를 만들어 보세요\n", "expectedOutput": "True",
        "classRequirements": {"name": "Student", "initParameterNames": ["name", "score"], "requiredMethods": ["is_passing"], "requiredAttributes": ["name", "score"], "testCases": [{"constructorArgs": ["민수", 65], "method": "is_passing", "expectedReturn": False}]},
        "hints": ["__init__에서 받은 score는 self.score에 저장해야 다른 메서드에서도 쓸 수 있습니다.", "is_passing에서는 self.score >= 70 비교 결과를 return합니다.", "class Student:\n    def __init__(self, name, score):\n        self.name = name\n        self.score = score\n\n    def is_passing(self):\n        return self.score >= 70\n\nprint(Student(\"피터\", 85).is_passing())"],
        "summary": "메서드는 객체가 기억한 속성으로 판단하고 결과를 돌려줄 수 있습니다.", "estimatedMinutes": 20,
    },
    {
        "id": "class-add-score", "order": 58, "level": 8, "unit": "클래스", "title": "객체에 점수 추가하기",
        "concept": "메서드는 self.속성을 바꾸어 객체의 상태를 변화시킬 수 있습니다.",
        "why": "새 점수가 들어올 때마다 목록을 밖에서 직접 다루지 않고, 학생 객체에게 ‘점수 추가’를 맡길 수 있어요.",
        "example": "class Student:\n    def __init__(self):\n        self.scores = []\n\n    def add_score(self, score):\n        self.scores.append(score)\n\nstudent = Student()\nstudent.add_score(80)\nstudent.add_score(95)\nprint(student.scores)", "exampleOutput": "[80, 95]",
        "prompt": "빈 scores 목록을 가진 Student 클래스를 만들고, add_score(score)가 점수를 목록에 추가하게 하세요. 80과 95를 추가한 목록을 출력해 보세요.",
        "starterCode": "# scores에 점수를 추가하는 Student 클래스를 만들어 보세요\n", "expectedOutput": "[80, 95]",
        "classRequirements": {"name": "Student", "initParameterNames": [], "requiredMethods": ["add_score"], "requiredAttributes": ["scores"], "testCases": [{"constructorArgs": [], "method": "add_score", "args": [77], "expectedAttribute": ["scores", [77]]}]},
        "hints": ["__init__에서 self.scores = []로 빈 목록을 만듭니다.", "리스트 끝에 값을 넣는 메서드는 self.scores.append(score)입니다.", "class Student:\n    def __init__(self):\n        self.scores = []\n\n    def add_score(self, score):\n        self.scores.append(score)\n\nstudent = Student()\nstudent.add_score(80)\nstudent.add_score(95)\nprint(student.scores)"],
        "summary": "메서드는 객체 안에 저장된 목록을 안전하게 바꾸는 창구가 됩니다.", "estimatedMinutes": 21,
    },
    {
        "id": "class-average", "order": 59, "level": 8, "unit": "클래스", "title": "객체가 자기 평균 계산하기",
        "concept": "객체 안의 scores 목록을 메서드에서 반복하면, 객체 스스로 평균을 계산하게 만들 수 있습니다.",
        "why": "데이터와 그 데이터를 처리하는 로직을 가까이 두면 코드를 읽기 쉬워집니다.",
        "example": "class Student:\n    def __init__(self, scores):\n        self.scores = scores\n\n    def average(self):\n        total = 0\n        for score in self.scores:\n            total += score\n        return total / len(self.scores)\n\nprint(Student([80, 90]).average())", "exampleOutput": "85.0",
        "prompt": "scores를 저장하는 Student 클래스를 만들고 average()가 scores 평균을 돌려주게 하세요. [80, 90]의 결과를 출력해 보세요.",
        "starterCode": "# scores를 사용하는 average 메서드를 만들어 보세요\n", "expectedOutput": "85.0",
        "classRequirements": {"name": "Student", "initParameterNames": ["scores"], "requiredMethods": ["average"], "requiredAttributes": ["scores"], "requiresFor": True, "testCases": [{"constructorArgs": [[60, 80, 100]], "method": "average", "expectedReturn": 80.0}]},
        "hints": ["__init__의 scores를 self.scores에 저장합니다.", "average 안에서 total을 만들고 self.scores를 반복한 뒤 len(self.scores)로 나눕니다.", "class Student:\n    def __init__(self, scores):\n        self.scores = scores\n\n    def average(self):\n        total = 0\n        for score in self.scores:\n            total += score\n        return total / len(self.scores)\n\nprint(Student([80, 90]).average())"],
        "summary": "객체의 메서드는 그 객체가 가진 데이터에 맞는 작업을 담당합니다.", "estimatedMinutes": 23,
    },
    {
        "id": "class-add-xp", "order": 60, "level": 8, "unit": "클래스", "title": "경험치를 누적하는 학습자",
        "concept": "self.xp = self.xp + amount처럼 속성의 이전 값과 새 값을 계산하면 상태를 누적할 수 있습니다.",
        "why": "게임의 점수, 장바구니 수량, 학습 경험치처럼 계속 변하는 값을 객체가 기억하게 할 수 있어요.",
        "example": "class Learner:\n    def __init__(self):\n        self.xp = 0\n\n    def add_xp(self, amount):\n        self.xp = self.xp + amount\n\nlearner = Learner()\nlearner.add_xp(15)\nprint(learner.xp)", "exampleOutput": "15",
        "prompt": "xp를 0으로 시작하는 Learner 클래스를 만들고 add_xp(amount)가 xp를 늘리게 하세요. 15를 더한 xp를 출력해 보세요.",
        "starterCode": "# xp를 기억하고 늘리는 Learner 클래스를 만들어 보세요\n", "expectedOutput": "15",
        "classRequirements": {"name": "Learner", "initParameterNames": [], "requiredMethods": ["add_xp"], "requiredAttributes": ["xp"], "testCases": [{"constructorArgs": [], "method": "add_xp", "args": [7], "expectedAttribute": ["xp", 7]}]},
        "hints": ["처음 xp는 __init__ 안에서 self.xp = 0으로 만듭니다.", "새 값을 덮어쓸 때는 self.xp의 이전 값에 amount를 더합니다.", "class Learner:\n    def __init__(self):\n        self.xp = 0\n\n    def add_xp(self, amount):\n        self.xp = self.xp + amount\n\nlearner = Learner()\nlearner.add_xp(15)\nprint(learner.xp)"],
        "summary": "객체의 속성은 메서드 호출 사이에도 값을 기억합니다.", "estimatedMinutes": 19,
    },
    {
        "id": "class-study-timer", "order": 61, "level": 8, "unit": "클래스", "title": "공부 상태를 가진 타이머",
        "concept": "클래스가 필요한 때는 여러 값이 함께 움직이고, 그 값을 다루는 행동도 함께 있을 때입니다.",
        "why": "단순한 계산 하나는 함수가 알맞고, 시작·종료처럼 상태가 변하는 대상은 클래스로 표현하기 좋습니다.",
        "example": "class StudyTimer:\n    def __init__(self):\n        self.running = False\n\n    def start(self):\n        self.running = True\n        print(\"공부 시작\")\n\ntimer = StudyTimer()\ntimer.start()", "exampleOutput": "공부 시작",
        "prompt": "running을 False로 시작하는 StudyTimer 클래스를 만들고, start()가 running을 True로 바꾼 뒤 “공부 시작”을 출력하게 하세요.",
        "starterCode": "# 상태를 바꾸는 StudyTimer 클래스를 만들어 보세요\n", "expectedOutput": "공부 시작",
        "classRequirements": {"name": "StudyTimer", "initParameterNames": [], "requiredMethods": ["start"], "requiredAttributes": ["running"], "testCases": [{"constructorArgs": [], "method": "start", "expectedOutput": "공부 시작", "expectedAttribute": ["running", True]}]},
        "hints": ["running의 첫 값은 __init__에서 self.running = False로 만듭니다.", "start 메서드에서는 self.running = True를 먼저 실행한 뒤 안내 문장을 출력합니다.", "class StudyTimer:\n    def __init__(self):\n        self.running = False\n\n    def start(self):\n        self.running = True\n        print(\"공부 시작\")\n\ntimer = StudyTimer()\ntimer.start()"],
        "summary": "클래스는 상태(속성)와 행동(메서드)을 한 설계도에 묶습니다.", "estimatedMinutes": 20,
    },
    {
        "id": "class-course-students", "order": 62, "level": 8, "unit": "클래스", "title": "코스에 학생 등록하기",
        "concept": "한 객체 안에 리스트를 속성으로 두면, 관련된 여러 값을 차례로 모을 수 있습니다.",
        "why": "코스 객체가 학생 목록을 직접 관리하면, 목록 변수를 여기저기 전달하지 않아도 됩니다.",
        "example": "class Course:\n    def __init__(self):\n        self.students = []\n\n    def add_student(self, name):\n        self.students.append(name)\n\ncourse = Course()\ncourse.add_student(\"피터\")\nprint(course.students)", "exampleOutput": "['피터']",
        "prompt": "빈 students 목록을 가진 Course 클래스를 만들고 add_student(name)가 이름을 추가하게 하세요. 피터를 등록한 목록을 출력해 보세요.",
        "starterCode": "# 학생 목록을 관리하는 Course 클래스를 만들어 보세요\n", "expectedOutput": "['피터']",
        "classRequirements": {"name": "Course", "initParameterNames": [], "requiredMethods": ["add_student"], "requiredAttributes": ["students"], "testCases": [{"constructorArgs": [], "method": "add_student", "args": ["민수"], "expectedAttribute": ["students", ["민수"]]}]},
        "hints": ["__init__에서 self.students = []로 빈 목록을 준비합니다.", "add_student에서는 self.students.append(name)으로 전달받은 이름을 넣습니다.", "class Course:\n    def __init__(self):\n        self.students = []\n\n    def add_student(self, name):\n        self.students.append(name)\n\ncourse = Course()\ncourse.add_student(\"피터\")\nprint(course.students)"],
        "summary": "객체는 관련된 목록과 목록을 바꾸는 기능을 함께 관리할 수 있습니다.", "estimatedMinutes": 20,
    },
    {
        "id": "class-report-mission", "order": 63, "level": 8, "unit": "미니 미션", "title": "학생 성적 보고 객체",
        "concept": "한 클래스에 이름·점수 목록·평균 메서드·통과 메서드를 넣으면 학생 한 명의 분석 규칙이 완성됩니다.",
        "why": "앞에서 만든 함수들을 서로 관련된 데이터와 함께 묶는 것이 객체지향 설계의 첫걸음입니다.",
        "example": "class StudentReport:\n    def __init__(self, name, scores):\n        self.name = name\n        self.scores = scores\n\n    def average(self):\n        total = 0\n        for score in self.scores:\n            total += score\n        return total / len(self.scores)\n\n    def is_passing(self):\n        return self.average() >= 70\n\nreport = StudentReport(\"피터\", [80, 90])\nprint(report.average())", "exampleOutput": "85.0",
        "prompt": "name과 scores를 저장하는 StudentReport 클래스를 만들고 average(), is_passing() 메서드를 완성하세요. 피터 [80, 90]의 average 결과를 출력해 보세요.",
        "starterCode": "# StudentReport 클래스에 average와 is_passing 메서드를 만들어 보세요\n", "expectedOutput": "85.0",
        "classRequirements": {"name": "StudentReport", "initParameterNames": ["name", "scores"], "requiredMethods": ["average", "is_passing"], "requiredAttributes": ["name", "scores"], "requiresFor": True, "testCases": [{"constructorArgs": ["민수", [50, 60]], "method": "is_passing", "expectedReturn": False}]},
        "hints": ["average는 self.scores를 반복해 합계를 만들고 평균을 return합니다.", "is_passing은 self.average()의 결과가 70 이상인지 return하면 됩니다.", "class StudentReport:\n    def __init__(self, name, scores):\n        self.name = name\n        self.scores = scores\n\n    def average(self):\n        total = 0\n        for score in self.scores:\n            total += score\n        return total / len(self.scores)\n\n    def is_passing(self):\n        return self.average() >= 70\n\nreport = StudentReport(\"피터\", [80, 90])\nprint(report.average())"],
        "summary": "클래스는 관련 데이터와 분석 기능을 한 덩어리로 정리합니다.", "estimatedMinutes": 27,
    },
    # Level 9 starts module design in the single-editor environment. A true
    # multi-file editor is deliberately a later UI feature, documented in docs/.
    {
        "id": "module-import-math", "order": 64, "level": 9, "unit": "모듈", "title": "모듈에서 원주율 가져오기",
        "concept": "모듈은 관련 기능을 모아 둔 파이썬 파일입니다. import로 모듈을 가져오면 점(.) 뒤에서 기능과 값을 쓸 수 있습니다.",
        "why": "이미 검증된 기능을 직접 다시 만들지 않고, 코드의 역할을 파일별로 나누는 출발점이 됩니다.",
        "example": "import math\nprint(math.pi)", "exampleOutput": "3.141592653589793",
        "prompt": "math 모듈을 import하고 math.pi를 출력해 보세요.",
        "starterCode": "# math 모듈을 가져와 원주율을 출력해 보세요\n", "expectedOutput": "3.141592653589793",
        "codeRequirements": {"requiredSyntax": ["import"], "requiredImports": ["math"]},
        "hints": ["파일 위쪽에 import math를 작성합니다.", "모듈 안의 값은 math.pi처럼 모듈 이름과 점을 붙여 씁니다.", "import math\nprint(math.pi)"],
        "summary": "import math는 math.py에 있는 기능과 값을 현재 코드에서 쓰게 합니다.", "estimatedMinutes": 13,
    },
    {
        "id": "module-from-import", "order": 65, "level": 9, "unit": "모듈", "title": "필요한 함수만 가져오기",
        "concept": "from math import sqrt처럼 쓰면, 모듈 전체 대신 필요한 이름 하나를 현재 코드에 가져옵니다.",
        "why": "코드에서 어떤 기능을 쓰는지 더 뚜렷하게 보이고, 긴 모듈 이름을 반복하지 않아도 됩니다.",
        "example": "from math import sqrt\nprint(sqrt(81))", "exampleOutput": "9.0",
        "prompt": "math에서 sqrt를 가져와 81의 제곱근을 출력해 보세요.",
        "starterCode": "# sqrt를 가져와 81에 사용해 보세요\n", "expectedOutput": "9.0",
        "codeRequirements": {"requiredCalls": ["sqrt"], "requiredSyntax": ["importFrom"], "requiredImports": ["math"]},
        "hints": ["from math import sqrt로 기능 이름을 가져옵니다.", "sqrt를 가져왔다면 sqrt(81)처럼 바로 호출합니다.", "from math import sqrt\nprint(sqrt(81))"],
        "summary": "from ... import ...는 필요한 도구 하나를 골라 가져오는 방식입니다.", "estimatedMinutes": 13,
    },
    {
        "id": "module-rules-function", "order": 66, "level": 9, "unit": "모듈", "title": "게임 규칙을 함수로 분리하기",
        "concept": "모듈로 나누기 전에는 먼저 ‘입력’, ‘규칙 판단’, ‘출력’처럼 서로 다른 역할을 구분해야 합니다.",
        "why": "가위바위보에서 승패 판단을 함수로 분리해 두면, 나중에 rules.py로 옮겨도 main 코드는 거의 바뀌지 않아요.",
        "example": "def is_draw(user, computer):\n    return user == computer\n\nprint(is_draw(\"가위\", \"가위\"))", "exampleOutput": "True",
        "prompt": "두 선택이 같으면 True를 돌려주는 is_draw(user, computer) 함수를 만들고 가위·가위의 결과를 출력해 보세요.",
        "starterCode": "# 나중에 rules.py로 옮길 is_draw 함수를 만들어 보세요\n", "expectedOutput": "True",
        "functionRequirements": {"name": "is_draw", "parameterCount": 2, "parameterNames": ["user", "computer"], "requiresReturn": True, "testCases": [{"args": ["바위", "보"], "expectedReturn": False}]},
        "hints": ["무승부 규칙은 두 값이 같은지 비교하는 한 줄입니다.", "규칙 함수는 print 대신 비교 결과를 return해 다른 파일에서도 쓰기 좋게 만듭니다.", "def is_draw(user, computer):\n    return user == computer\n\nprint(is_draw(\"가위\", \"가위\"))"],
        "summary": "나중에 모듈로 옮길 규칙은 출력보다 반환값 중심으로 만들면 재사용하기 쉽습니다.", "estimatedMinutes": 15,
    },
    {
        "id": "module-random-opponent", "order": 67, "level": 9, "unit": "모듈", "title": "상대 선택은 random에 맡기기",
        "concept": "기능의 책임을 나누면, 무작위 선택은 random 모듈이 담당하고 우리 코드는 게임 규칙에 집중할 수 있습니다.",
        "why": "직접 만들 필요 없는 기능을 표준 라이브러리에 맡기는 것도 좋은 모듈화 습관입니다.",
        "example": "import random\nchoices = [\"가위\", \"바위\", \"보\"]\ncomputer = random.choice(choices)\nprint(computer)", "exampleOutput": "가위 또는 바위 또는 보",
        "prompt": "random 모듈에 상대 선택을 맡기세요. choices에서 random.choice()로 computer를 만들고 출력해 보세요.",
        "starterCode": "choices = [\"가위\", \"바위\", \"보\"]\n# random 모듈에 상대 선택을 맡겨 보세요\n", "expectedOutput": "", "checkType": "non_empty_output",
        "codeRequirements": {"requiredVariableNames": ["choices", "computer"], "requiredSyntax": ["list", "import"], "requiredImports": ["random"], "requiredAttributeCalls": ["choice"]},
        "hints": ["무작위 선택 기능은 import random으로 가져옵니다.", "선택한 결과는 computer = random.choice(choices)로 변수에 저장합니다.", "import random\nchoices = [\"가위\", \"바위\", \"보\"]\ncomputer = random.choice(choices)\nprint(computer)"],
        "summary": "모듈은 프로그램의 각 부분이 자기 역할에 집중하게 도와줍니다.", "estimatedMinutes": 15,
    },
    {
        "id": "module-constants", "order": 68, "level": 9, "unit": "모듈", "title": "바뀌지 않는 값에 이름 붙이기",
        "concept": "상수는 프로그램 곳곳에서 같은 의미로 쓰는 값을 한곳에 모아 둔 이름입니다. 실제 프로젝트에서는 constants.py로 옮길 수 있습니다.",
        "why": "기준 점수처럼 바뀔 수 있는 규칙을 한 곳에서 관리하면 숫자를 찾아 바꾸는 실수를 줄일 수 있어요.",
        "example": "PASS_SCORE = 70\nscore = 85\nprint(score >= PASS_SCORE)", "exampleOutput": "True",
        "prompt": "PASS_SCORE에 70을 저장하고 score 85가 통과인지 출력해 보세요.",
        "starterCode": "# 기준 점수를 PASS_SCORE라는 이름에 저장해 보세요\n", "expectedOutput": "True",
        "codeRequirements": {"requiredVariableNames": ["PASS_SCORE", "score"], "requiredOperators": ["greaterOrEqual"]},
        "hints": ["바뀌지 않는 기준값은 대문자 이름 PASS_SCORE에 저장합니다.", "score >= PASS_SCORE 비교식을 print로 출력합니다.", "PASS_SCORE = 70\nscore = 85\nprint(score >= PASS_SCORE)"],
        "summary": "의미 있는 이름의 상수는 규칙을 읽기 쉽고 바꾸기 쉽게 합니다.", "estimatedMinutes": 14,
    },
    {
        "id": "module-main-guard", "order": 69, "level": 9, "unit": "모듈", "title": "직접 실행할 때만 시작하기",
        "concept": "if __name__ == \"__main__\":은 파일을 직접 실행했을 때만 시작 코드를 실행하게 하는 관용구입니다.",
        "why": "다른 파일에서 함수를 import할 때는 게임이나 테스트가 자동으로 시작되지 않게 할 수 있어요.",
        "example": "if __name__ == \"__main__\":\n    print(\"프로그램 시작\")", "exampleOutput": "프로그램 시작",
        "prompt": "if __name__ == \"__main__\": 아래에서 “프로그램 시작”을 출력해 보세요.",
        "starterCode": "# 직접 실행할 때만 출력하도록 main guard를 작성해 보세요\n", "expectedOutput": "프로그램 시작",
        "codeRequirements": {"requiredSyntax": ["if"], "requiresMainGuard": True},
        "hints": ["__name__은 파이썬이 파일 실행 방식을 알려 주는 특별한 이름입니다.", "조건문 아래 print는 한 단계 들여써야 합니다.", "if __name__ == \"__main__\":\n    print(\"프로그램 시작\")"],
        "summary": "main guard는 가져다 쓰는 코드와 직접 실행하는 코드를 분리합니다.", "estimatedMinutes": 16,
    },
    {
        "id": "module-page-calculator", "order": 70, "level": 9, "unit": "모듈", "title": "계산 도구 모듈 사용하기",
        "concept": "ceil처럼 이미 준비된 계산 도구를 import하면, 복잡한 올림 규칙을 직접 구현하지 않아도 됩니다.",
        "why": "한 페이지에 10개씩 담을 때 필요한 페이지 수 같은 실무 계산을 정확하고 간단하게 처리할 수 있어요.",
        "example": "from math import ceil\nitem_count = 23\nprint(ceil(item_count / 10))", "exampleOutput": "3",
        "prompt": "math에서 ceil을 가져오고 item_count 23개를 한 페이지에 10개씩 담을 때 필요한 페이지 수를 출력해 보세요.",
        "starterCode": "item_count = 23\n# ceil을 가져와 필요한 페이지 수를 출력해 보세요\n", "expectedOutput": "3",
        "codeRequirements": {"requiredVariableNames": ["item_count"], "requiredCalls": ["ceil"], "requiredSyntax": ["importFrom"], "requiredImports": ["math"], "requiredOperators": ["divide"]},
        "hints": ["페이지 수는 item_count / 10을 올림하면 됩니다.", "ceil을 쓰려면 from math import ceil이 먼저 필요합니다.", "from math import ceil\nitem_count = 23\nprint(ceil(item_count / 10))"],
        "summary": "필요한 계산 도구를 모듈에서 가져오면 코드가 짧고 의도가 분명해집니다.", "estimatedMinutes": 16,
    },
    {
        "id": "module-rps-mission", "order": 71, "level": 9, "unit": "미니 미션", "title": "가위바위보 규칙 모듈 완성",
        "concept": "작은 프로젝트는 입력·무작위 선택·규칙 판단·출력으로 나눌 수 있습니다. 여기서는 그중 rules.py로 옮길 승패 규칙을 완성합니다.",
        "why": "규칙을 함수 하나로 독립시키면 화면 출력 방식이 바뀌어도 게임의 핵심 판단 코드는 재사용할 수 있어요.",
        "example": "def determine_result(user, computer):\n    if user == computer:\n        return \"무승부\"\n    if user == \"가위\" and computer == \"보\":\n        return \"승리\"\n    return \"패배\"\n\nprint(determine_result(\"가위\", \"보\"))", "exampleOutput": "승리",
        "prompt": "determine_result(user, computer)를 만드세요. 같으면 “무승부”, user가 가위이고 computer가 보이면 “승리”, 나머지는 “패배”를 돌려주고 가위·보 결과를 출력해 보세요.",
        "starterCode": "# rules.py 역할의 determine_result 함수를 완성해 보세요\n", "expectedOutput": "승리",
        "functionRequirements": {"name": "determine_result", "parameterCount": 2, "parameterNames": ["user", "computer"], "requiresReturn": True, "requiresIf": True, "testCases": [{"args": ["바위", "바위"], "expectedReturn": "무승부"}, {"args": ["보", "가위"], "expectedReturn": "패배"}]},
        "hints": ["가장 먼저 같은지 확인해 무승부를 return합니다.", "그 다음 user가 가위이고 computer가 보인 특별한 승리 조건을 and로 연결합니다.", "def determine_result(user, computer):\n    if user == computer:\n        return \"무승부\"\n    if user == \"가위\" and computer == \"보\":\n        return \"승리\"\n    return \"패배\"\n\nprint(determine_result(\"가위\", \"보\"))"],
        "summary": "규칙 함수를 분리하면 작은 게임도 역할이 선명한 프로그램으로 자랍니다.", "estimatedMinutes": 24,
    },
]
